### PR TITLE
Extend XLA Python interface to allow dumping computations to HTML

### PR DESCRIPTION
**Pull request by andportnoy**
The motivation is to enable a scriptable alternative to `interactive_graphviz`. This PR contains the bare minimum needed to dump computation subgraphs to HTML and allows one to write scripts like the following:

```python
import sys
from jax._src.lib import xla_extension as xla
​
# path to HLO txt
filename = sys.argv[1]
​
with open(filename) as file:
    # existing function to load module from string
    module = xla.hlo_module_from_text(file.read())
​
# the following was added
# - module.computations()
# - computation.name
# - computation.render_html(filename)
for comp in module.computations():
    if "fusion" in comp.name:
        comp.render_html(comp.name)
```

### CODE REVIEW

**Review by jvstokes — APPROVED** [review]
Thank you, Andrey!

**Review by jvstokes — APPROVED** [review]

**Review by jvstokes — CHANGES_REQUESTED** [review]
Could you please update the typedefs in `xla/python/xla_extension/__init__.pyi` to reflect your ComputationWrapper class? Thank you!

**Comment by andportnoy** [comment]
@jvstokes, ah, will do! Thanks for taking a look.

**Comment by andportnoy** [comment]
@jvstokes done, thank you.

**Review by jvstokes — APPROVED** [review]
Looks good, thank you!

**Pull request closed without merging**
