### PR TITLE
[PJRT:GPU] Respect auto layout modes in MLIR compilation

### PR DESCRIPTION
**Pull request by jaro-sevcik**
Without this patch, auto layouts for arguments and results turn into default layouts (in the
DetermineArgumentLayoutsFromCompileOptions function). This patch avoids calling
DetermineArgumentLayoutsFromCompileOptions from the MLIR compilation method
so that empty layouts on shapes are preserved.

With this patch we should be able to enable four more layout tests in JAX on GPUs.

### CODE REVIEW

**Review by ezhulenev — APPROVED** [review]

**Comment by nouiz** [comment]
The PR dot approved, but not merged. Any idea what is going on?

**Comment by akuegel** [comment]
> The PR dot approved, but not merged. Any idea what is going on?

We always need approval by two different people, and only Eugene approved both on GitHub and internally. Therefore merging was blocked, it would have required a different person to approve internally.

@xla-rotation please follow up on getting this PR merged

**Review by akuegel — APPROVED** [review]
Approving again to recreate the internal change for merging.

**Comment by akuegel** [comment]
@jaro-sevcik we get a test failure in 3 of the Jax tests:

INVALID_ARGUMENT: Cannot serialize ExecutableBuildOptions::layout_canonicalization_callback

The tests in question are:

https://github.com/google/jax/blob/main/tests/aot_test.py

https://github.com/google/jax/blob/main/tests/pgle_test.py

https://github.com/google/jax/blob/main/tests/compilation_cache_test.py

Any idea how to fix this?

**Comment by jaro-sevcik** [comment]
Thank you for sharing the failures. I have a good idea where this is coming from. Let me fix this tomorrow.

**Comment by jaro-sevcik** [comment]
@akuegel I have added a small (but somewhat ugly) fix to the PR. Could you take a look?

Alternatively, I could pass the layout callback to the CompileInternal method and set it on the compile options only after we take a copy of the compile options for the executable. Please let me know if that's preferable.

**Comment by akuegel** [comment]
> @akuegel I have added a small (but somewhat ugly) fix to the PR. Could you take a look?
> 
> Alternatively, I could pass the layout callback to the CompileInternal method and set it on the compile options only after we take a copy of the compile options for the executable. Please let me know if that's preferable.

I will defer to others here, I am not so familiar with the PJRT stuff. @ezhulenev what do you think?

**Comment by jaro-sevcik** [comment]
I have added the callback as an argument to the CompileInternal method. It does look cleaner.

@ezhulenev , could you take a look, please?

**Review by ezhulenev — APPROVED** [review]

**Pull request closed without merging**
