### PR TITLE
build gpu plugin

### PR DESCRIPTION
**Pull request by jyingl3**

### CODE REVIEW

**Comment by gbaned** [comment]
Hi @jyingl3 This PR is in draft, any update on this? Please. Thank you!

**Comment by gbaned** [comment]
Hi @jyingl3 Any update on this PR? Please.  Thank you!

**Comment by kamaljeeti** [comment]
Hi @jyingl3,
Any update on this PR? Please. Thank you!

**Comment by dimitar-asenov** [comment]
It seems that this PR has been abandoned as there has been no activity for several months now. I will close it. In case you want to nevertheless merge this PR, please update to the latest code state and resolve the issues listed above. Thanks!

**Pull request closed without merging**
