### PR TITLE
[ROCm] Fix Build break due to f4212dc and 0f75900

### PR DESCRIPTION
**Pull request by hsharsha**
This fixes build break due to f4212dc and 0f75900

### CODE REVIEW

**Comment by hsharsha** [comment]
@xla-rotation  @penpornk  please prioritize this.

**Review by ddunl — APPROVED** [review]

**Comment by penpornk** [comment]
@hsharsha We have other code that depends on `Client::XlaComputationInstance` so we prefer keeping the `using` statement. Could you please share the error log and the command to reproduce? Does this only happen to the ROCm build? Are there some other ways to fix this?

**Comment by hsharsha** [comment]
@penpornk  this is the error with `-fpermissive`
```
In file included from xla/client/client.cc:16:
  ./xla/client/client.h:43:9: error: declaration of ‘using XlaComputationInstance = struct xla::XlaComputationInstance’ changes meaning of ‘XlaComputationInstance’ [-fpermissive]
     43 |   using XlaComputationInstance = XlaComputationInstance;
        |         ^~~~~~~~~~~~~~~~~~~~~~
  In file included from ./xla/client/client.h:29,
                 from xla/client/client.cc:16:
    116 | struct XlaComputationInstance {
      |        ^~~~~~~~~~~~~~~~~~~~~~
```

**Comment by hsharsha** [comment]
@penpornk I am not able to understand the purpose of redefinition of `using XlaComputationInstance = XlaComputationInstance;`
Should it be `Server::XlaComputationInstance`?

**Comment by d0k** [comment]
> @penpornk I am not able to understand the purpose of redefinition of `using XlaComputationInstance = XlaComputationInstance;` Should it be `Server::XlaComputationInstance`?

It's so users can keep using `Client::XlaComputationInstance`. What you're seeing is a GCC bug, a possible workaround is `using XlaComputationInstance = xla::XlaComputationInstance;`.

The last time I saw this the argument was that building XLA with GCC instead of Clang is an unsupported configuration.

**Review by penpornk — APPROVED** [review]
Thank you for the changes!

**Comment by penpornk** [comment]
Closing this as @klucke made more changes internally and merged it as https://github.com/openxla/xla/commit/13e073933546b90feb641c42edbe70bfbc206ea0. 
(Sorry the original author credit didn't go through!)

**Pull request closed without merging**
