### PR TITLE
[GPU] cuDNN GEMM: add support of slicing of inputs.

### PR DESCRIPTION
**Pull request by sergachev**

### CODE REVIEW

**Review by bchetioui — APPROVED** [review]

**Comment by sergachev** [comment]
Thank you for reviewing! Please do not merge yet because the PR it depends on got [reverted](https://github.com/openxla/xla/pull/16098).

**Comment by sergachev** [comment]
The required version of cuDNN frontend is [in](https://github.com/openxla/xla/pull/16291). This one is ready to be merged now!

**Comment by sgerrard** [comment]
@sergachev There is an internal error, could you fix it? 

[third_party/tensorflow/compiler/xla/service/gpu/transforms/cudnn_fusion_compiler.cc:436](https://cs.corp.google.com/piper///depot/google3/third_party/tensorflow/compiler/xla/service/gpu/transforms/cudnn_fusion_compiler.cc?l=436&ws=tap-presubmit-server/236337774&snapshot=2):40: error: no member named 'slice' in 'cudnn_frontend::graph::Graph'
  436 |       hlo_to_cudnn[&parameter] = graph.slice(
      |                                  ~~~~~ ^
[third_party/tensorflow/compiler/xla/service/gpu/transforms/cudnn_fusion_compiler.cc:438](https://cs.corp.google.com/piper///depot/google3/third_party/tensorflow/compiler/xla/service/gpu/transforms/cudnn_fusion_compiler.cc?l=438&ws=tap-presubmit-server/236337774&snapshot=2):18: error: no member named 'Slice_attributes' in namespace 'cudnn_frontend::graph'
  438 |           graph::Slice_attributes().set_slices(dims.slices.value()));
      |           ~~~~~~~^
2 errors generated.

**Comment by sergachev** [comment]
This means that Google's internal version of the cuDNN frontend did not get upgraded together with https://github.com/openxla/xla/pull/16291. You can find previous mentions of this process for example here https://github.com/openxla/xla/pull/9376.

**Pull request closed without merging**
