### PR TITLE
Add the host memory deallocation in GpuExecutor::Deallocate

### PR DESCRIPTION
**Pull request by zhenying-liu**
This CL adds the missing host memory deallocation according to the pointer's host memory space allocated by GpuExecutor::Allocate() .

### CODE REVIEW

**Comment by zhenying-liu** [comment]
The AMD ROCm failure seems not related with the current CL:
`xla/service/gpu/fusions/triton/compilation_pipeline_rocm.cc:110:33: error: ‘createOptimizeLdsUsagePass’ is not a member of ‘mlir::triton::AMD’; did you mean ‘createOptimizeLDSUsagePass’?`

**Review by ezhulenev — APPROVED** [review]

**Comment by ezhulenev** [comment]
Can you please add a test that fails without this change

**Comment by zhenying-liu** [comment]
> Can you please add a test that fails without this change

Yes, will do.

**Review by ezhulenev — APPROVED** [review]

**Comment by sgerrard** [comment]
I am getting the following build error on our internal tests: [third_party/tensorflow/compiler/xla/stream_executor/cuda/cuda_executor.cc:489] :3: error: void function 'Deallocate' should not return a value [-Wreturn-mismatch]

**Comment by zhenying-liu** [comment]
> I am getting the following build error on our internal tests: [third_party/tensorflow/compiler/xla/stream_executor/cuda/cuda_executor.cc:489] :3: error: void function 'Deallocate' should not return a value [-Wreturn-mismatch]
I will take a look.

**Review by ezhulenev — APPROVED** [review]

**Pull request closed without merging**
