### PR TITLE
Switch to use compiler param file for msvc

### PR DESCRIPTION
**Pull request by cloudhan**
These changes make the nvcc wrapper for msvc to fully support command file for msvc.

Previously, multiple `command is longer than CreateProcessW's limit (32767 characters)` errors pop up here and there due to the excessive `_virtual_includes` introduced by mlir.

This makes
1. the wrapper to accept a params file, that is, `<wrapper.bat> <params_file>
2. the wrapper to generate filtered params file (command file as of msvc if you want to search it) for the successive msvc invocation, `<params_file> -->filter--> <msvc_param_file>`), that is in `<wrapper.py>`, we call `Popen(<msvc>, <msvc_param_file>)`

### CODE REVIEW

**Comment by tpopp** [comment]
@ddunl can you ensure someone from your team is aware of this change how ever much you find appropriate? @jakeharmon8 I think you're the most knowledgeable on this after recent work, so can you share your thoughts on this change, even if you don't do the detailed review?

**Comment by cloudhan** [comment]
Note, the <wrapper.bat> is added to workaround 
```bash
# msvc_cl_path
#   /
python.exe -B <wrapper.py> [[option1]...]
#          \--- write to file.params ---/

# then invoked with 
python.exe @file.params  # This is ill-formed!!!!!!

# file.params
-B
<wrapper.py>
option1
...
```

with `<wrapper.bat>`
```bash
# <wrapper.bat>
python.exe -B <wrapper.py> %s

# msvc_cl_path
#   /
<wrapper.bat> [[option1]...]
#               \--- write to file.params 

# then invoked with 
<wrapper.bat> @file.params

# file.params
option1
...
```

**Comment by yashk2810** [comment]
@hawkinsp should probably look at this.

**Comment by hawkinsp** [comment]
I have no particular knowledge here. This looks good to me but @jakeharmon8 is probably the right person to review.

Perhaps @tlongeri also?

**Comment by cloudhan** [comment]
How about just trigger one run and see if it goes well? There is no external dependency at all and the logic is trivial as described in the comment https://github.com/openxla/xla/pull/2843#issuecomment-1537976051

**Comment by ddunl** [comment]
Today's my first day back, so I still may not get to patching this by the end of this week. If you check on this PR next week and there's no further activity, please tag me again! Sorry for the delay.

**Review by ddunl — APPROVED** [review]

**Comment by ddunl** [comment]
Sorry for the delay, working on landing this now. I'll update with any issues should they arise

**Pull request closed without merging**
