### PR TITLE
[ROCm] Add Swizzle instruction support for mi100+ in reduction fusion shuffle-down function

### PR DESCRIPTION
**Pull request by Ruturaj4**
[ROCm] Add Swizzle instruction support for mi100+ in reduction fusion shuffle-down function.

### CODE REVIEW

**Comment by Ruturaj4** [comment]
@ddunl @xla-rotation : would you take a look please?

**Comment by Ruturaj4** [comment]
Hello, @ddunl @xla-rotation is there any update on this?

**Review by akuegel — COMMENTED** [review]
Can you please add a test? Could be a .hlo test in xla/service/gpu/tests directory.

**Comment by Ruturaj4** [comment]
> Can you please add a test? Could be a .hlo test in xla/service/gpu/tests directory.

Thanks. I updated existing tests. There are few other test failures, but in `xla/service/gpu/tests` on ROCm. However, they fail for other reasons. We will send patches fixing them one by one.

**Review by akuegel — APPROVED** [review]

**Pull request closed without merging**
