### PR TITLE
[GPU] GEMM fusions: let fusing effective parameters and their broadcasts in the epilogues.

### PR DESCRIPTION
**Pull request by sergachev**

### CODE REVIEW

**Review by bchetioui — APPROVED** [review]

**Comment by loislo** [comment]
gemm_fusion_autotuner fails in a few tests 

F1030 15:35:52.295284     614 gemm_fusion_autotuner.cc:1041] Non-OK-status: has_executable.status()
Status: FAILED_PRECONDITION: Can not propagate dim orders and requirements.
=== Source Location Trace: ===
[third_party/tensorflow/compiler/xla/util.h:279][third_party/tensorflow/compiler/xla/service/gpu/triton_fusion_analysis.cc:164][third_party/tensorflow/compiler/xla/service/gpu/triton_fusion_analysis.cc:285][third_party/tensorflow/compiler/xla/service/gpu/triton_fusion_analysis.cc:197][third_party/tensorflow/compiler/xla/service/gpu/fusions/triton/triton_fusion_emitter_legacy_matmul.cc:1978][third_party/tensorflow/compiler/xla/service/gpu/fusions/triton/triton_fusion_emitter.cc:1113][third_party/tensorflow/compiler/xla/service/gpu/fusions/triton/triton_fusion_emitter.cc:1170][third_party/tensorflow/compiler/xla/service/gpu/fusions/triton.cc:105][third_party/tensorflow/compiler/xla/service/gpu/fusions/triton.cc:137][third_party/tensorflow/compiler/xla/service/gpu/fusions/triton.cc:212][third_party/tensorflow/compiler/xla/service/gpu/ir_emitter_unnested.cc:1505][third_party/tensorflow/compiler/xla/service/gpu/ir_emitter_unnested.cc:2942][third_party/tensorflow/compiler/xla/service/gpu/compile_module_to_llvm_ir.cc:256][third_party/tensorflow/compiler/xla/service/gpu/gpu_compiler.cc:2250][third_party/tensorflow/compiler/xla/service/gpu/gpu_compiler.cc:2366][third_party/tensorflow/compiler/xla/service/gpu/autotuning/gemm_fusion_autotuner.cc:974]Failure occured when compiling fusion gemm_fusion_dot.1811 with config '{block_m:64,block_n:16,block_k:32,split_k:16,num_stages:1,num_warps:4,num_ctas:1}'

**Comment by sergachev** [comment]
Which ones? gemm_fusion_autotuner_test and xla/service/gpu/fusions/triton/... pass.

**Comment by loislo** [comment]
> Which ones? gemm_fusion_autotuner_test and xla/service/gpu/fusions/triton/... pass.

the internal test for gemini

**Comment by sergachev** [comment]
I didn't guess yet what's the reason. Could you share the HLO of the failing fusion? Or maybe just its epilogue without shapes?

**Comment by loislo** [comment]
> I didn't guess yet what's the reason. Could you share the HLO of the failing fusion? Or maybe just its epilogue without shapes?

The HLO has
dot = dot(param_0, param_1)
bitcast = bitcast(dot)
transpose = transpose(bitcast)
convert = convert(transpose)
param_2 = param(2)
bitcast_2 = bitcast(param_2)
broadcast = broadcast(bitcast_2)
convert_2 = convert(broadcast)
multiply = multiply(convert, convert_2)
ROOT convert_3 = convert(multiply)

**Pull request closed without merging**
