### PR TITLE
Fix multi gpu spmd core

### PR DESCRIPTION
**Pull request by mars1248**
During multi-GPU training, using spmd optimization, coredum is triggered。Refer to this issue for the reproduction method：https://github.com/pytorch/xla/issues/6225

### CODE REVIEW

**Comment by kamaljeeti** [comment]
Hi @mars1248, can you sign up for this CLA provided below.
https://cla.developers.google.com/clas

**Comment by mars1248** [comment]
> Hi @mars1248, can you sign up for this CLA provided below. https://cla.developers.google.com/clas

I've already registered

**Comment by cheshire** [comment]
@hawkinsp @jurahul for review. 

Could you provide additional motivation/testing for the change?  From the linked issue it seems to avoid a segfault during training execution from PT/XLA, but it's a bit hard to see how exactly?

**Comment by kamaljeeti** [comment]
Hi @hawkinsp, @jurahul, can you please check @cheshire's commnents and provide additional comments or review it? Thank you!

**Comment by mars1248** [comment]
@cheshire 
Hello, my PR for this fix is mainly due to the core dump caused by running spmd in multi-GPU training. 
I'm going to locate what's generated here
https://github.com/pytorch/xla/blob/0cd6f1052db2421b3a77b602aba351c607f33480/torch_xla/csrc/runtime/pjrt_computation_client.cc#L692-L698.
So I wrote pjrt_stream_executor_client_cuda_test as a single test from the associated issue reproduces the problem.
And I found that when gpu is running, each process can only get `addressable_device_logical_ids_[0].replica` and `addressable_device_logical_ids_[0].partition`, So I added a new interface to openxla to implement local execute and successfully avoid core dump.
I'm also curious why this call `(*returned_futures)[0].OnReady`causes core dump
cc @vanbasten23

**Comment by cheshire** [comment]
Thanks, I see !  Do you know why do we have this crash for PT/XLA, but not for JAX? Is PT/XLA using a different PJRT entry point? Maybe it can use the same entry point as JAX and avoid the issue altogether?

**Comment by vanbasten23** [comment]
Added some discussion https://github.com/pytorch/xla/issues/6225#issuecomment-1877877753 .

> Do you know why do we have this crash for PT/XLA, but not for JAX?

Afaict, PT/XLA uses the GPU client the same way as JAX (with the prerequisite fix such as https://github.com/pytorch/xla/pull/6266). The crash happens at https://github.com/pytorch/xla/blob/e1c94dfa5a74331a376537c23bf74a2c367f24bd/torch_xla/csrc/runtime/pjrt_computation_client.cc#L692 which merely reset the timer and nothing else. I found if we comment out `(*returned_futures)[0].OnReady(`, we get the expected result. But as what @mars1248 said, we need to find out why it crashed or why the future becomes invalid.

**Comment by mars1248** [comment]
@cheshire 
Thanks for your interest, we have located the issue with torchxla spmd and successfully fixed it with this pr https://github.com/pytorch/xla/pull/6275
cc @vanbasten23

**Pull request closed without merging**
