### PR TITLE
[ROCm] Do not use fast approximation for exp and log

### PR DESCRIPTION
**Pull request by mmakevic-amd**
Error started occurring from this commit for exp https://github.com/openxla/xla/commit/6e9eefeec077f49c2b22bfeee8da537ed8517b22 (originally introduced here https://github.com/openxla/xla/commit/9b19353a30821fb990afa456a2a5e7fae71e9afc#diff-61ab646c9c3b8b0fc5ed1e9a62f535e9df5843adddd071250343f3bec48eacb6) and from this one https://github.com/openxla/xla/commit/53d533845f3c97d08a49e3d8589ec98c745ac09e for log.

Trying to compile following MLIR code:
```
HloModule module

ENTRY main {
      p0 = bf16[4] parameter(0)
      ROOT exp = bf16[4] exp(p0)
}
```
would result in:
```
UNKNOWN: <unknown>:0: error: loc(callsite("wrapped_exponential" at "wrapped_exponential")): failed to legalize operation 'math.exp'
<unknown>:0: note: loc("wrapped_exponential"): called from
<unknown>:0: note: loc(callsite("wrapped_exponential" at "wrapped_exponential")): see current operation: %7 = "math.exp"(%6) <{fastmath = #arith.fastmath<afn>}> : (bf16) -> bf16
```

### CODE REVIEW

**Comment by mmakevic-amd** [comment]
@akuegel I am aware of the underlying problem - https://github.com/llvm/llvm-project/pull/102971 (I noticed you pinged them already). I will revert this change once that is solved.

**Review by akuegel — APPROVED** [review]

**Review by golechwierowicz — COMMENTED** [review]
Can you add a unit test?

**Comment by akuegel** [comment]
@mmakevic-amd friendly ping regarding the unit test? You can create one here: https://github.com/openxla/xla/blob/main/xla/service/gpu/gpu_float_support_test.cc

**Comment by mmakevic-amd** [comment]
@akuegel @golechwierowicz Sorry for the wait, a test has been added

**Review by akuegel — APPROVED** [review]

**Pull request closed without merging**
