### PR TITLE
Do not default to sm_90a on non-Hopper platforms.

### PR DESCRIPTION
**Pull request by dimvar**

### CODE REVIEW

**Review by dimitar-asenov — CHANGES_REQUESTED** [review]
I know this is a minor change, but please add a test.

**Comment by dimvar** [comment]
Can you say more what kind of test you'd expect? This change is a no-op for publicly available platforms. It only takes effect on Blackwell onward.

**Comment by dimitar-asenov** [comment]
Sorry I forgot to mention this.

A simple unit test of the `GetSmName` function would do. That function simply takes a compute capability as input and outputs a string. It should be trivial to simply call this function with a few different compute capabilities and ensure that the correct string is returned. The fact that some CCs are unreleased shouldn't matter.

You will also have to expose this function in the header file to make it testable, that should be fine.

**Comment by dimvar** [comment]
Thanks for the clarification. Added a test. PTAL.

**Review by dimitar-asenov — APPROVED** [review]

**Comment by dimitar-asenov** [comment]
Thank you for adding the test, much appreciated.

LGTM.

**Comment by dimvar** [comment]
feedback/copybara failed but the "details" goes to an google-internal link to a CL. Can someone take a look?

**Comment by dimitar-asenov** [comment]
I did not manage to submit this yesterday (Zurich time) and am going away for a week today. 

I believe the issue is that the test target in the `BUILD` file is missing a dependency on:

```
"//third_party/tensorflow/compiler/xla/stream_executor:device_description",
```

@golechwierowicz Could you please take care of submitting this?

**Pull request closed without merging**
