### PR TITLE
[ROCm] Don't use CUDA PTX for ROCM in ComputationIdCmd

### PR DESCRIPTION
**Pull request by draganmladjenovic**

### CODE REVIEW

**Review by ezhulenev — APPROVED** [review]

**Comment by i-chaochen** [comment]
Hi @xla-rotation could you merge this PR now? thanks!

**Review by ezhulenev — APPROVED** [review]

**Comment by draganmladjenovic** [comment]
@ezhulenev What else needs to be done to push this trough?

**Review by ezhulenev — APPROVED** [review]

**Comment by ezhulenev** [comment]
Today is google-wide holiday, I think on Monday people will click the right buttons to merge this change

**Comment by draganmladjenovic** [comment]
Thanks for the info! Happy holiday.

**Comment by i-chaochen** [comment]
@xla-rotation gentle ping

**Comment by wenchenvincent** [comment]
@ezhulenev Is there anything blocking this PR? Let us know if there is anything needed from our side.

**Comment by kamaljeeti** [comment]
Hi @ddunl , can you look into this once? Thanks.

**Comment by tdanyluk** [comment]
I'll fix this internally, but please don't put member variables behind #ifdefs in headers.
If two targets include the header but define GOOGLE_CUDA differently, then the size of objects will not match between those targets.
(The fact that this can happen is a problem in XLA in general.)

**Pull request closed without merging**
