### PR TITLE
Set Asynchronous Custom Call Start Thunks

### PR DESCRIPTION
**Pull request by philipphack**
Corrects the types of the thunks emitted for asynchronous GEMM Custom Call starts.

### CODE REVIEW

**Comment by cheshire** [comment]
Was it working before? What is the behavior change?

**Comment by philipphack** [comment]
We want to emit cublasLT or cublasLT FP8 thunks based on the type of the wrapped call. Currently, all types of GEMM Custom Calls result in the emission of a legacy cublas thunk. This causes problems since legacy calls only support a subset of the features of cublasLT. For example, FP8 operands are not supported by legacy cublas and lead to an error without this change. Legacy thunks are still emitted [here](https://github.com/openxla/xla/blob/main/xla/service/gpu/ir_emitter_unnested.cc#L1728) when the type of the wrapped call matches.

**Comment by cheshire** [comment]
> For example, FP8 operands are not supported by legacy cublas and lead to an error without this change

Is it possible to write a test then?

**Comment by philipphack** [comment]
Yes, this is meant to be tested by WindowedEinsumE2EAllGatherAndReduceScatterF8 in collective_ops_test_e2e.cc. However, the dot merger pass prevented the GEMM rewriter from generating non-legacy custom calls. I've disabled the dot merger in the test. The test now fails without the changes in ir_emitter_unnested.cc.

**Comment by cheshire** [comment]
But collectives test is an e2e one, perhaps we could have a more isolated test?

**Review by ezhulenev — APPROVED** [review]

**Comment by penpornk** [comment]
@philipphack Could you please help rebase? collective_ops_test_e2e has been renamed.

**Comment by philipphack** [comment]
@penpornk Done.

**Pull request closed without merging**
