### PR TITLE
Fix a bug in AsyncAllocator memory pools access setting.

### PR DESCRIPTION
**Pull request by buptzyb**
The original code uses the wrong parameter `i` for `cuDeviceCanAccessPeer()`, which can cause undefined behavior when `(*all_ids_)[i] != platform_device_id`, for example, virtual devices are used. Should use `(*all_ids_)[i].value()` to represent the previous pool id.

Also, add a judgment to skip the pool initialization process if it's already initialized previously. This can happen in some cases, such as when multiple virtual devices are created from one physical GPU, the virtual devices will actually share the same CUDA memory pool.

Same PR from TensorFlow repo: https://github.com/tensorflow/tensorflow/pull/67373.

### CODE REVIEW

**Review by ezhulenev — APPROVED** [review]

**Review by akuegel — APPROVED** [review]
Approving again, the imported change has been garbage collected by now

**Comment by akuegel** [comment]
@xla-rotation the internal version of this change has been garbage collected again. I didn't check what was blocking the merge.

**Comment by penpornk** [comment]
@buptzyb Apologies for the delay! This branch now has conflicts. Could you please help resolve them? We'll look into merging the PR again soon after.

**Comment by buptzyb** [comment]
@penpornk Hi, I resolved the conflicts. Thanks!

**Comment by akuegel** [comment]
Can you please also write a test?

**Comment by buptzyb** [comment]
> Can you please also write a test?

Add a test that creates two allocators on one GPU and lets them share the default pool. Without this fix the test would fail.

**Review by akuegel — APPROVED** [review]
Thank you

**Pull request closed without merging**
