### PR TITLE
[GPU] Cleanup handling of determinism settings.

### PR DESCRIPTION
**Pull request by sergachev**
TF_CUDNN_DETERMINISTIC is TF-specific and will be handled there.

Merge all checks of determinism flags in RequireDeterminism().
Set NumericOptions.require_determinism using it.

### CODE REVIEW

**Review by cheshire — CHANGES_REQUESTED** [review]
Overall direction makes sense, but is it possible to provide a more expanded description? Are any user-visible controls changing?

**Comment by sergachev** [comment]
>but is it possible to provide a more expanded description?
Added some.

>Are any user-visible controls changing?
No.

**Comment by sergachev** [comment]
ping

**Review by cheshire — APPROVED** [review]

**Comment by dimitar-asenov** [comment]
This PR breaks a Tensorflow determinism test:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/kernel_tests/nn_ops/cudnn_d9m_test.py

@sergachev Could you please have a look?

**Comment by sergachev** [comment]
I see, TF uses for example StreamExecutor's GetConvolveRunners directly: https://github.com/tensorflow/tensorflow/blob/21cb99df4daccd139c4e7137367e5e76239b743e/tensorflow/core/kernels/conv_ops_gpu.cc#L291. I'll then propose a patch to TF which will move the handling of TF_CUDNN_DETERMINISTIC completely into TF.

**Comment by dimitar-asenov** [comment]
Thank you, Ilia. Please let me know once that patch is in and I can merge the PR.

**Review by reedwm — APPROVED** [review]

**Comment by sergachev** [comment]
The TF change is done: https://github.com/tensorflow/tensorflow/commit/3f8a0eed4a40a6888c2713f11db92804c33b2f18, this one is now ready.

**Review by reedwm — APPROVED** [review]

**Pull request closed without merging**
