### PR TITLE
[STACKED PR] [XLA:GPU][NFC] Rename Triton autotuner to GEMM fusion autotuner.

### PR DESCRIPTION
**Pull request by sergachev**
// Testing stacked PRs.

As discussed during the addition of the cuDNN GEMM fusion backend the autotuner pass can have a better name now.

### CODE REVIEW

**Review by tdanyluk — APPROVED** [review]
thanks

**Comment by sergachev** [comment]
Is this PR blocked by anything @tdanyluk @dimitar-asenov?

**Comment by dimitar-asenov** [comment]
I think there was some issue with the internal system and we didn't get the internal CL on time. Now it has conflicts, could you please rebase and then I can merge it.

**Comment by sergachev** [comment]
Rebased.

**Comment by dimitar-asenov** [comment]
Thank you.

**Review by dimitar-asenov — APPROVED** [review]

**Pull request closed without merging**
