### PR TITLE
[XLA:GPU] Error out for ptxas version - Update ptxas version check

### PR DESCRIPTION
**Pull request by AyanmoI**
The version check is extended to all ptxas version `12.3.103`

### CODE REVIEW

**Comment by sergeykozub** [comment]
What is the purpose of this PR?
It looks like it will match 12.3.1 as well as 12.3.10, but not 12.3.9 - why do we want it like that?

**Comment by AyanmoI** [comment]
> What is the purpose of this PR? It looks like it will match 12.3.1 as well as 12.3.10, but not 12.3.9 - why do we want it like that?

There may be an issue some ptxas versions but I am still investigating to narrow down the scope. I'll update the PR.

**Comment by kamaljeeti** [comment]
Hi @AyanmoI, any update on this PR? Thanks.

**Comment by akuegel** [comment]
> > What is the purpose of this PR? It looks like it will match 12.3.1 as well as 12.3.10, but not 12.3.9 - why do we want it like that?
> 
> There may be an issue some ptxas versions but I am still investigating to narrow down the scope. I'll update the PR.

Just to confirm, the issue is just with 12.3.103, not with 12.3.1 what was checked before?

**Comment by AyanmoI** [comment]
> > > What is the purpose of this PR? It looks like it will match 12.3.1 as well as 12.3.10, but not 12.3.9 - why do we want it like that?
> > 
> > 
> > There may be an issue some ptxas versions but I am still investigating to narrow down the scope. I'll update the PR.
> 
> Just to confirm, the issue is just with 12.3.103, not with 12.3.1 what was checked before?

That is correct. The issue is only with 12.3.103. We were investigating internally and based on current results, the issue is with .103.

**Review by tdanyluk — APPROVED** [review]

**Pull request closed without merging**
