### PR TITLE
[Code style]clean header guards from TensorFlow

### PR DESCRIPTION
**Pull request by GHGmc2**
To follow Google C++ style guide: https://google.github.io/styleguide/cppguide.html#The__define_Guard

### CODE REVIEW

**Comment by ddunl** [comment]
Good spot! Unfortunately these will probably stay like this for ~another month as these reflect where the code still lives internally. We're working on fixing this ASAP, but there's some things blocking the internal move currently. @tpopp to confirm I'm getting this right.

**Comment by ddunl** [comment]
On second thought, I can fix this, but unfortunately I don't think I'll be able to do it via this PR. I'll have to update the script that copies this code to github to transform the include guards, as merging this PR would change the include guards internally, which we don't want to do quite yet. I'll work on that and be sure to include your PR in the description!

**Review by tpopp — APPROVED** [review]
Thanks for your contribution :)

**Comment by ddunl** [comment]
The Check Contents failure is an error that I must've introduced, and I'm not convinced the CPU failures are related to this PR, so I'm going to import

**Comment by ddunl** [comment]
Working on patching a few things internally, the patched version should land soon. This will also be a good test to make sure that the patched change correctly attributes you as the author!

**Comment by GHGmc2** [comment]
> Working on patching a few things internally, the patched version should land soon. This will also be a good test to make sure that the patched change correctly attributes you as the author!

Thanks, then should I close this one?

**Comment by ddunl** [comment]
Please keep this one open! It should show that this one is merged when my patched version lands internally. I'll be submitting it tomorrow morning!

**Comment by ddunl** [comment]
Fantastic! Everything worked as expected. The reason why the diff in https://github.com/openxla/xla/commit/5d8f791c1b1183d7ccf637903ac937f161d1e953 is a bit different is due to a modifications I made: mlir-hlo uses different include guard style, so they don't need to be changed, there were a few extraneous changes on macros starting with `XLA_...`, and looking carefully I found some extra include guards that were formatted incorrectly prior to your change (e.g. missing comment after the `#endif`). 

Thanks so much for your PR!!

**Pull request closed without merging**
