### PR TITLE
moved from tsl::errors::Internal to absl::AbortedError

### PR DESCRIPTION
**Pull request by zstreet87**
Happy New Year!

Here is the requested API changed from my previous PR. 

See https://github.com/openxla/xla/pull/7575#pullrequestreview-1769997780

@i-chaochen @thomasjoerg @ddunl

### CODE REVIEW

**Comment by ddunl** [comment]
Thanks!! I think that using `absl::InternalError` would be better. My guess is (?) that on our end there's a check to use the `absl::` API directly and that it references `AbortedError` as an example and that's why it was given as the fix on that review. But @thomasjoerg please correct me if I am mistaken!!

**Comment by thomasjoerg** [comment]
> My guess is (?) that on our end there's a check to use the absl:: API directly and that it references AbortedError as an example and that's why it was given as the fix on that review. But @thomasjoerg please correct me if I am mistaken!!

That's exactly right.

**Comment by zstreet87** [comment]
cc: @ddunl @golechwierowicz

**Review by ddunl — APPROVED** [review]

**Comment by ddunl** [comment]
I think it needs rebase but should be good to go after that. Thanks!!

**Review by ddunl — APPROVED** [review]
Thanks!!

**Comment by zstreet87** [comment]
lmk if anything else is preventing this from being merged @ddunl @golechwierowicz

**Comment by ddunl** [comment]
Should be good, it should be merged in ~a couple hours

**Pull request closed without merging**
