### PR TITLE
Add python bindings for xla_gpu_experimental_autotune_cache_mode

### PR DESCRIPTION
**Pull request by trevor-m**
Adds python bindings for DebugOptions.xla_gpu_experimental_autotune_cache_mode so that it can be set via JAX. See https://github.com/jax-ml/jax/pull/22899

### CODE REVIEW

**Review by cheshire — APPROVED** [review]

**Comment by trevor-m** [comment]
@cheshire Thanks for reviewing and approving! The clang-format check seems to be failing on some part of the file that this PR didn't modify - just wanted to make sure that wasn't blocking this from getting merged.

**Review by golechwierowicz — APPROVED** [review]

**Comment by nouiz** [comment]
@golechwierowicz 
clang CI check failed on lines not touched by this PR. Any idea how to fix this?
Rebase the PR?

**Comment by loislo** [comment]
CheckLint found errors.
Undefined variable 'AutotuneCacheMode' [undefined-variable]
	//depot/[google3/third_party/tensorflow/compiler/xla/python/xla_client_test.py:3381:58](http://google3/third_party/tensorflow/compiler/xla/python/xla_client_test.py?l=3381)

**Comment by trevor-m** [comment]
> CheckLint found errors. Undefined variable 'AutotuneCacheMode' [undefined-variable] xla/python/xla_client_test.py:3381:58

Thanks @golechwierowicz for letting me know. I've pushed a change to fix this. I was wondering why we didn't see this in the CI results - is it an internal check? Or was the clang-format error prematurely exiting the CI pipeline and preventing this from running?

**Review by loislo — APPROVED** [review]

**Pull request closed without merging**
