### PR TITLE
Fix tan inaccuracies on complex inputs with large and small absolute values

### PR DESCRIPTION
**Pull request by pearu**
As in the title.

Tan evaluation is verified against mpmath tan function. The corresponding unit tests are included in xla/tests/complex_unary_op_test.cc 

When https://github.com/google/jax/pull/20688 lands, the follow-up PR will enable Tan tests at complex infinities.

### CODE REVIEW

**Comment by ddunl** [comment]
Assuming this is the same as the other one, please tag me once the JAX PR gets merged and I'll merge this PR. Thanks!!

**Comment by cheshire** [comment]
What is the status, we are still waiting for the JAX PR to get merged?

**Comment by pearu** [comment]
> What is the status, we are still waiting for the JAX PR to get merged?

Yes, this is blocked by https://github.com/google/jax/pull/20144#issuecomment-1995174058 and I am working on it atm.

**Comment by kamaljeeti** [comment]
Hi @pearu , any update on this PR? Thanks.

**Comment by pearu** [comment]
> Hi @pearu , any update on this PR? Thanks.

I am waiting for https://github.com/openxla/xla/pull/10503 to land as it implements unit-tests framework that this PR should use for testing `tan` fixes.

**Comment by pearu** [comment]
@cheshire @kamaljeeti , please review.

**Review by akuegel — APPROVED** [review]

**Pull request closed without merging**
