### PR TITLE
Fix BUILD files to allow building //xla/service/gpu/... in OSS

### PR DESCRIPTION
**Pull request by sergey-kozub**
Currently the following doesn't work in OSS:
$ bazel build //xla/service/gpu/...

with the PR applied, one can now build all targets.

### CODE REVIEW

**Comment by ddunl** [comment]
Approving but I'm suspicious that deleting the gunit_for_test_only will work. But I'll get the internal tests running to find out at least

**Review by ddunl — APPROVED** [review]

**Comment by ddunl** [comment]
Yeah it won't quite work like this, but after https://github.com/openxla/xla/pull/13746 which is really a Copybara change, we can submit the `service/gpu/tests` change

**Comment by ddunl** [comment]
I think now if you rebase we can submit the remaining changes

**Comment by sergey-kozub** [comment]
Something went wrong after merging. Created a new PR#13798

**Pull request closed without merging**
