### PR TITLE
[GPU] Upgrade cuDNN frontend to v1.2.0.

### PR DESCRIPTION
**Pull request by sergachev**
This will for instance allow fusion of scalar constants.

### CODE REVIEW

**Comment by reedwm** [comment]
@dimitar-asenov, you updated the internal version of cuDNN frontend for the last upgrade: https://github.com/openxla/xla/pull/9376. Do you want to do this again?

**Comment by dimitar-asenov** [comment]
Sure.

**Review by dimitar-asenov — APPROVED** [review]

**Comment by tdanyluk** [comment]
@dimitar-asenov Can we merge this now? Or is this waiting for something?

**Comment by dimitar-asenov** [comment]
I ran some tests last week and see some results which I'm not sure are fully OK, so I pinged someone internally to check. Unfortunately, they are OOO until 19 March, so it will be another 1-2 days.

**Comment by dimitar-asenov** [comment]
So I got the OK, but noticed after a sync that cudnn_frontend doesn't compile. I am encountering the same issue as described in this cudnn_frontend PR:

https://github.com/NVIDIA/cudnn-frontend/pull/56

I can only look into this in more detail in a day, but it seems like newer compilers might flag a legitimate error that was overseen in the past.

**Comment by sergachev** [comment]
Could you provide your exact error messages? Build errors in https://github.com/NVIDIA/cudnn-frontend/pull/56#issuecomment-1900492383 are from catch2 but XLA does not build files using it at all (https://github.com/openxla/xla/blob/main/third_party/cudnn_frontend.BUILD).

I didn't manage to reproduce any build failure yet with the latest clang 19.0.0 (20240318), C++ standard 20 or 23.

**Comment by dimitar-asenov** [comment]
Here is the exact message:

```
In file included from cudnn_frontend/samples/cpp/dgrads.cpp:23:
In file included from /catch2/catch.hpp:477:
In file included from stl/cxx17/string:8:
In file included from crosstool/v18/stable/toolchain/bin/../include/c++/v1/string:587:
In file included from crosstool/v18/stable/toolchain/bin/../include/c++/v1/__memory/allocate_at_least.h:13:
crosstool/v18/stable/toolchain/bin/../include/c++/v1/__memory/allocator_traits.h:329:5: error: no matching function for call to '__construct_at'
  329 |     std::__construct_at(__p, std::forward<_Args>(__args)...);
      |     ^~~~~~~~~~~~~~~~~~~
crosstool/v18/stable/toolchain/bin/../include/c++/v1/vector:903:21: note: in instantiation of function template specialization 'std::allocator_traits<std::allocator<std::shared_ptr<cudnn_frontend::graph::INode>>>::construct<std::shared_ptr<cudnn_frontend::graph::INode>, std::unique_ptr<cudnn_frontend::graph::MatmulNode>, void, 0>' requested here
  903 |     __alloc_traits::construct(this->__alloc(), std::__to_address(__tx.__pos_), std::forward<_Args>(__args)...);
      |                     ^
crosstool/v18/stable/toolchain/bin/../include/c++/v1/vector:1526:5: note: in instantiation of function template specialization 'std::vector<std::shared_ptr<cudnn_frontend::graph::INode>>::__construct_one_at_end<std::unique_ptr<cudnn_frontend::graph::MatmulNode>>' requested here
 1526 |     __construct_one_at_end(std::forward<_Args>(__args)...);
      |     ^
/cudnn_frontend/include/cudnn_frontend/node/../node_interface.h:247:19: note: in instantiation of function template specialization 'std::vector<std::shared_ptr<cudnn_frontend::graph::INode>>::emplace_back<std::unique_ptr<cudnn_frontend::graph::MatmulNode>>' requested here
  247 |         sub_nodes.emplace_back(std::make_unique<MatmulNode>(std::move(attributes), context));
      |                   ^
crosstool/v18/stable/toolchain/bin/../include/c++/v1/__memory/construct_at.h:47:46: note: candidate template ignored: substitution failure [with _Tp = std::shared_ptr<cudnn_frontend::graph::INode>, _Args = <std::unique_ptr<cudnn_frontend::graph::MatmulNode>>]: no matching constructor for initialization of 'std::shared_ptr<cudnn_frontend::graph::INode>'
   46 | template <class _Tp, class... _Args, class = decltype(::new(std::declval<void*>()) _Tp(std::declval<_Args>()...))>
      |                                                                                    ~~~
   47 | _LIBCPP_HIDE_FROM_ABI _LIBCPP_CONSTEXPR _Tp* __construct_at(_Tp* __location, _Args&&... __args) {
      |
```

I didn't see this last week when I was doing tests with your PR, so it's likely it's some internal update to a new clang version. I have a whole-day event today going into the evening, so I can't look until tomorrow.

**Comment by sergachev** [comment]
> In file included from cudnn_frontend/samples/cpp/dgrads.cpp:23:

You are trying to build samples here which again are not built or used by XLA at all: https://github.com/openxla/xla/blob/5e5c7b97d21e3c182622ddf11202038d74d4972a/third_party/cudnn_frontend.BUILD#L16  To skip building samples, use -DCUDNN_FRONTEND_BUILD_SAMPLES=OFF on cmake.

The build error you get is in library catch2 which is external to cudnn-frontend. CMake build downloads a specific version of it: https://github.com/NVIDIA/cudnn-frontend/blob/e5fb0edbf4d39145c1fbc3baec548f06e2b15d4c/samples/CMakeLists.txt#L12. If you are not using CMake please verify that you are using the same version of catch2 if you want to build samples.

**Comment by dimitar-asenov** [comment]
Sorry for the delay, I'm now back to looking into this.

> You are trying to build samples here which again are not built or used by XLA at all

XLA itself does not use the samples, but we use them internally as tests. So when we import a new version of CUDNN the samples must build and run correctly.

> The build error you get is in library catch2

Apologies for pasting a sample that contained catch2. The actual error is completely unrelated to catch2 or the samples. If I just try to compile the main CUDNN code, I already get an error in `include/cudnn_frontend/node_interface.h`. Here's another cleaner message:

```
In module '//third_party/crosstool/v18/stable:stl_cc_library':
third_party/crosstool/v18/stable/toolchain/bin/../include/c++/v1/__memory/allocator_traits.h:329:5: error: no matching function for call to '__construct_at'
  329 |     std::__construct_at(__p, std::forward<_Args>(__args)...);
      |     ^~~~~~~~~~~~~~~~~~~
third_party/crosstool/v18/stable/toolchain/bin/../include/c++/v1/vector:903:21: note: in instantiation of function template specialization 'std::allocator_traits<std::allocator<std::shared_ptr<cudnn_frontend::graph::INode>>>::construct<std::shared_ptr<cudnn_frontend::graph::INode>, std::unique_ptr<cudnn_frontend::graph::MatmulNode>, void, 0>' requested here
  903 |     __alloc_traits::construct(this->__alloc(), std::__to_address(__tx.__pos_), std::forward<_Args>(__args)...);
      |                     ^
third_party/crosstool/v18/stable/toolchain/bin/../include/c++/v1/vector:1526:5: note: in instantiation of function template specialization 'std::vector<std::shared_ptr<cudnn_frontend::graph::INode>>::__construct_one_at_end<std::unique_ptr<cudnn_frontend::graph::MatmulNode>>' requested here
 1526 |     __construct_one_at_end(std::forward<_Args>(__args)...);
      |     ^
./third_party/cudnn_frontend/include/cudnn_frontend/node/../node_interface.h:247:19: note: in instantiation of function template specialization 'std::vector<std::shared_ptr<cudnn_frontend::graph::INode>>::emplace_back<std::unique_ptr<cudnn_frontend::graph::MatmulNode>>' requested here
  247 |         sub_nodes.emplace_back(std::make_unique<MatmulNode>(std::move(attributes), context));
      |                   ^
third_party/crosstool/v18/stable/toolchain/bin/../include/c++/v1/__memory/construct_at.h:47:46: note: candidate template ignored: substitution failure [with _Tp = std::shared_ptr<cudnn_frontend::graph::INode>, _Args = <std::unique_ptr<cudnn_frontend::graph::MatmulNode>>]: no matching constructor for initialization of 'std::shared_ptr<cudnn_frontend::graph::INode>'
   46 | template <class _Tp, class... _Args, class = decltype(::new(std::declval<void*>()) _Tp(std::declval<_Args>()...))>
      |                                                                                    ~~~
   47 | _LIBCPP_HIDE_FROM_ABI _LIBCPP_CONSTEXPR _Tp* __construct_at(_Tp* __location, _Args&&... __args) {
      |
``` 
I will see if there is a quick way to patch this internally, but it would be good to have an upstream fix. I suspect this error only happens with clang that's reasonably close to latest mainline version.

**Comment by sergachev** [comment]
>  I suspect this error only happens with clang that's reasonably close to latest mainline version.

The one I tried is the latest possible built 3 days ago:
> the latest clang 19.0.0 (20240318), C++ standard 20 or 23.

Could you also paste your `clang --version` please?

**Comment by ilya-biryukov** [comment]
> The one I tried is the latest possible built 3 days ago:

Could it be that  libc++ or libstdc++ used during the compilation were of versions that did not have full C++20 `constexpr` overhaul? The failure definitely happens with Clang 16, 17 and 18 and here is a simplified example: https://gcc.godbolt.org/z/5b6Pdxsjd.

I've also left a similar comment on the PR that fixes compilation of cudnn here:
https://github.com/NVIDIA/cudnn-frontend/pull/56#issuecomment-2012291108

**Comment by sergachev** [comment]
@ilya-biryukov Thank you for the clarification! Indeed `-stdlib=libc++` is sufficient to reproduce this.

**Comment by dimitar-asenov** [comment]
Update: I've used @ilya-biryukov's patch internally to move to cudnn_frontend 1.2.1. I'm now in the process of merging a modified version of this PR that will also move OpenXLA to v 1.2.1. It should hopefully land today.

**Pull request closed without merging**
