### PR TITLE
Sm 90a

### PR DESCRIPTION
**Pull request by zhenying-liu**
Fix a ptxas failure: replace the target of sm_90 with sm_90a.

### CODE REVIEW

**Review by cheshire — CHANGES_REQUESTED** [review]
Could you provide some more context? Which HLOs are currently crashing on sm90?

**Comment by zhenying-liu** [comment]
It's at the end of all the HLOs, when the PTX assembler is called to assemble the code. The driver only knows the major and minor version: 9 and 0. But PTX defines the target name sm_90a. Some advanced features/extensions can only be assembled with sm_90a target, not sm_90. So it crashed at the run time: 
external/xla/xla/pjrt/pjrt_stream_executor_client.cc:2537] Execution of replica 0 failed: INTERNAL: Failed to execute XLA Runtime executable: run time error: custom call 'xla.gpu.custom_call' failed: ptxas exited with non-zero error code 65280, output: ptxas fatal: PTX with .target 'sm_90a' cannot be compiled for architecture 'sm_90'

**Comment by joker-eph** [comment]
@cheshire : I believe it is not an HLO issue but a Triton problem, that is Triton will codegen for sm_90a but ptxas is invoked by XLA somehow in your integration and it does not match? 
It showed up with JAX-Triton, so it may be specific to JAX-Triton integration and I don't know if it would hit with Triton-as-an-HLO-backend (you should have a better idea than me on how this is plumbed together).

**Review by cheshire — APPROVED** [review]
A test would be nice though.

**Comment by tdanyluk** [comment]
When I was doing a test on hopper, we also had to replace the target sm in the generated PTX.
Not sure if still needed but good to know if you hit further problems.

In EmitModuleToPTX:
```
// Triton's PTXTranslation.cpp does the same:
ptx = tsl::str_util::StringReplace(ptx, "\n.target sm_90\n",
                                    "\n.target sm_90a\n",
                                    /*replace_all=*/false);
```

**Comment by joker-eph** [comment]
The problem is downstream from PTX here, it happens when handling the ptx tagged with sm_90a in ptxas.

The string replacement problem you had to do seems to indicate an issue in LLVM upstream instead? Or with how llvm is initialized.
The string replacement in PTX should work here, but it really does not seem very principled or clean.

**Comment by ddunl** [comment]
@zhenying-liu Thanks for your PR!! I think you have to accept the CLA before we can import and merge this change

**Comment by zhenying-liu** [comment]
Thanks @ddunl. I got my CLA signed. Please import and merge the change. Thanks!

**Review by ddunl — APPROVED** [review]

**Pull request closed without merging**
