### PR TITLE
[NVIDIA] Fix XLA build with the new cuDNN

### PR DESCRIPTION
**Pull request by kaixih**
This PR fixes a couple of minor issues to support the XLA build against the cuDNN v9.

cc. @reedwm

### CODE REVIEW

**Review by reedwm — APPROVED** [review]
Note that internally, we still have the [cudnn_8_0.inc](https://github.com/tensorflow/tensorflow/blob/132c98b29c1a42298cd13055d1168c8d67177bc9/third_party/xla/third_party/tsl/tsl/cuda/cudnn_8_0.inc) file that was removed by commit tensorflow/tensorflow@132c98b29c1a42298cd13055d1168c8d67177bc9. When we upgrade to cuDNN 9 internally, we might need a new cudnn_9_0.inc file, and update the functions with the ones you added in this PR.

Anyway, nothing we have to worry about yet.

**Comment by kaixih** [comment]
@reedwm It seems this PR is still pending and I didn't see the changes are reflected in the main branch yet.

**Comment by reedwm** [comment]
It looks like the changes to [xla/service/gpu/conv_algorithm_picker.cc](https://github.com/openxla/xla/blob/main/xla/service/gpu/conv_algorithm_picker.cc) went through, but not the changes to [third_party/tsl/tsl/cuda/cudnn.symbols](https://github.com/openxla/xla/blob/main/third_party/tsl/tsl/cuda/cudnn.symbols).

@ddunl do you know what to do here? Presumably the TSL change cannot be made through the XLA repo. The [google/tsl](https://github.com/google/tsl) repo README states TSL changes should be made in the TensorFlow repo, but links to a non-existent directory in the TensorFlow repo.

**Comment by akuegel** [comment]
I have merged the missing pieces manually in https://github.com/openxla/xla/commit/d68614b66df53af91f9503e4031034c869f2c861

**Pull request closed without merging**
