### PR TITLE
[XLA:GPU] Fix cuDNN version check.

### PR DESCRIPTION
**Pull request by sergachev**

### CODE REVIEW

**Review by kamaljeeti — APPROVED** [review]
LGTM.

**Review by reedwm — APPROVED** [review]

**Comment by kamaljeeti** [comment]
Hi @reedwm , there are some internal checks failing. Can you have a look at it once? Thanks.

**Comment by akuegel** [comment]
@beckerhe also fixed this, so this can be closed.

**Comment by sergachev** [comment]
The comment was left inconsistent though: https://github.com/openxla/xla/commit/2fd1f08f94cc159aacd7f596e50d045a6d39fb50#diff-bf32dc375d56847bafb9e8170ac2ea2e9e606ed6e402be5f21fb40de384bdf1bR381

**Comment by beckerhe** [comment]
My bad. Fix is coming.

**Pull request closed without merging**
