### PR TITLE
[GPU] Support pointwise floor and ceil in GEMM fusions.

### PR DESCRIPTION
**Pull request by sergachev**
For this to work with Triton openxla/triton will need to include https://github.com/openai/triton/commit/62706e8c518c8c56e56460a43732d8e375217860.

### CODE REVIEW

**Comment by Moerafaat** [comment]
The change looks good, though the needed Triton change would need to be included as you mentioned. I will cherry-pick your change internally so that it reflects on OpenXLA/Triton and then you can merge this change.

**Comment by Moerafaat** [comment]
@sergachev The required dependency change now applies on top of OpenXLA/xla so this should be unblocked.

**Review by Moerafaat — APPROVED** [review]

**Comment by sergachev** [comment]
//xla/service/gpu:softmax_rewriter_triton_test fails, I'm looking at that

**Comment by dimitar-asenov** [comment]
Thanks @sergachev. Please ping me when you fix the issue and I will merge the PR internally.

**Comment by sergachev** [comment]
@dimitar-asenov it's fixed now

**Comment by dimitar-asenov** [comment]
@sergachev Actually, one more thing: Could you please add the new ops to this list:

https://github.com/openxla/xla/blob/main/xla/service/gpu/triton_support_test.cc#L193-L201

**Comment by sergachev** [comment]
OK, I added them, but could not test - this test does not build in OSS because of the known problem with bazel backend tags; if I hack them it fails on unknown EXPECT_OK and so on.

**Pull request closed without merging**
