### PR TITLE
Added datatype conversion helpers and error handling macros for cudnn frontend

### PR DESCRIPTION
**Pull request by shraiysh**

### CODE REVIEW

**Comment by shraiysh** [comment]
@googlebot rescan

**Comment by shraiysh** [comment]
Can someone please trigger a rescan for CLA? I had not added my email address to my profile. I have added it now and it should pass.

**Comment by AyanmoI** [comment]
@ezhulenev Can you please quickly take a look at this? I think @cheshire is OOO.

**Review by ezhulenev — APPROVED** [review]

**Comment by kamaljeeti** [comment]
Hi @ezhulenev, can you have a look once as it's already approved but it is still open. Thanks

**Review by ezhulenev — APPROVED** [review]

**Comment by shraiysh** [comment]
I do not see any merge conflicts - will this be automatically merged?

**Pull request closed without merging**
