### PR TITLE
[XLA:CPU] [oneDNN] Refactoring oneDNN Memory Util for Custom Call oneDNN Thunk Runtime Support

### PR DESCRIPTION
**Pull request by othakkar**
At thunk execution, the memory buffer info for oneDNN is created based on the shapes of the input arguments and the output results. This PR refactors the `onednn_memory_util` to create memory references from shape, which will be used in a separate PR to add custom call oneDNN thunk support.

### CODE REVIEW

**Review by penpornk — APPROVED** [review]
Thank you for the PR!

**Comment by penpornk** [comment]
Could you please help resolve merge conflicts? Thank you!
(Sorry for the delay in merging. Our internal presubmit infra had some issues that were blocking the merge until recently.)

**Comment by othakkar** [comment]
@penpornk, thanks for approving the PR! I resolved the merge conflicts.

**Review by penpornk — APPROVED** [review]
Thank you very much!

**Comment by othakkar** [comment]
@penpornk, it looks like the PR got closed without merging the commits. Could you please take a look?

**Comment by reedwm** [comment]
This actually was merged. For technical reasons, XLA PRs show up as closed even when they are merged. This was merged in commit 4d5f6913330cec7755205c18dc17f913325dedeb.

**Comment by othakkar** [comment]
Okay, I see. Thanks, @reedwm!

**Pull request closed without merging**
