### PR TITLE
[GPU][NFC] Add cuDNN 9.4.0 redistribution.

### PR DESCRIPTION
**Pull request by sergachev**

### CODE REVIEW

**Review by beckerhe — APPROVED** [review]

**Comment by johnnynunez** [comment]
and cuda 12.6.1?

**Comment by johnnynunez** [comment]
> > and cuda 12.6.1?
> 
> #17003

thanks! What about jetson packages? https://github.com/openxla/xla/issues/16912

**Comment by beckerhe** [comment]
@ddunl Is it expected that Copybara won't let us import this change?

**Comment by ddunl** [comment]
At the moment yes unfortunately. I'll patch it in today.

**Comment by sergachev** [comment]
ping

**Comment by ddunl** [comment]
https://github.com/openxla/xla/commit/0e994afa175ce5acda248f83a1569280a594bb22 It seems like Yulia already did this. Sorry for the delay! Closing for now.

**Pull request closed without merging**
