### PR TITLE
[ROCm] Make MLIR Math dialect lowering more deterministic

### PR DESCRIPTION
**Pull request by draganmladjenovic**
First apply patterns from GpuToROCDLConversionPatterns then do the cleanup with MathToLLVMConversionPatterns

### CODE REVIEW

**Review by akuegel — COMMENTED** [review]
Do you have an example where it is currently not deterministic?
I remember that currently we handle the conflict between lowering to LLVM and lowering to GPU specific functions by declaring several LLVM ops as illegal. I agree this is a bit of a hack, but I thought it works?

**Comment by draganmladjenovic** [comment]
Last time it was log1p/log/sqrt, but for time to time we had random crashes on other function changing between builds. If adding illegal ops fixes things I'm open going that way. Look by far cleaner. I need to check what happens when MathToLLVM tries to use unsupported op as part of lowering of a "complex" op.  What makes me uneasy I'm not quite clear if our bitcode implementation produces same results as the intrinsics, since unlike cuda our implementation is not a wrapper over intrinsic. So i chose to give priority to ROCDL patterns.

**Comment by akuegel** [comment]
> Last time it was log1p/log/sqrt, but for time to time we had random crashes on other function changing between builds. If adding illegal ops fixes things I'm open going that way. Look by far cleaner. I need to check what happens when MathToLLVM tries to use unsupported op as part of lowering of a "complex" op. What makes me uneasy I'm not quite clear if our bitcode implementation produces same results as the intrinsics, since unlike cuda our implementation is not a wrapper over intrinsic. So i chose to give priority to ROCDL patterns.

Ok, thanks for the explanation.

**Review by akuegel — APPROVED** [review]
Normally we require a test, but I think this can be counted as non-functional change (at least on Nvidia backend).

**Pull request closed without merging**
