### PR TITLE
[GPU] Support broadcasts in cuDNN GEMM fusions.

### PR DESCRIPTION
**Pull request by sergachev**
Stacked PR.

### CODE REVIEW

**Review by cheshire — CHANGES_REQUESTED** [review]
In my understanding, the tests test execution, but not building, of such fusions. Could we test the latter as well?

**Comment by sergachev** [comment]
All GEMM fusions that may go through cuDNN are currently constructed by the [GEMM fusion pass](https://github.com/openxla/xla/blob/main/xla/service/gpu/gemm_fusion.h) (ex GEMM rewriter Triton) in a mostly backend-agnostic way, that is well covered with [tests](https://github.com/openxla/xla/blob/main/xla/service/gpu/gemm_fusion_test.cc) - also for broadcasts; this commit does not modify that part.

**Review by cheshire — APPROVED** [review]

**Comment by cheshire** [comment]
Seems there are conflicts, could you rebase?

**Comment by sergachev** [comment]
Looks like stacked PRs require manual adjustments after base PRs are merged. Rebased and updated the target branch.

**Review by cheshire — APPROVED** [review]

**Comment by sergachev** [comment]
Was merged as part of https://github.com/openxla/xla/pull/10612

**Pull request closed without merging**
