### PR TITLE
[draft] Enable Relu epilogue fusion for FP8 cublasLt matmul for training

### PR DESCRIPTION
**Pull request by wenscarl**
As a supplement of PR [10977](https://github.com/openxla/xla/pull/10977).

### CODE REVIEW

**Comment by penpornk** [comment]
Hi @wenscarl, I noticed that the PR title has the word "[draft]". Are you still working on it or is this ready for review? If it's still WIP, could you please set its status to [draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests#draft-pull-requests)?

**Comment by wenscarl** [comment]
> Hi @wenscarl, I noticed that the PR title has the word "[draft]". Are you still working on it or is this ready for review? If it's still WIP, could you please set its status to [draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests#draft-pull-requests)?

Thanks for reminding. Changed as suggested.

**Comment by penpornk** [comment]
> Thanks for reminding. Changed as suggested.

Thank you very much!

**Comment by wenscarl** [comment]
Close because [PR-10977](https://github.com/openxla/xla/pull/10977) includes fp8 changes.

**Pull request closed without merging**
