### PR TITLE
[openxla][iree] Enable new runtime in OSS.

### PR DESCRIPTION
**Pull request by jpienaar**
This is WIP PR to enabling new runtime in OSS. There is no intention of enabling this yet, more to consider changes needed. Most are just manual to account for the different directory layouts and a repo dep.

Additional changes seen thus far:

- [ ] Using older version of LLVM predating Python change;
- [ ] Include directories of NCCL & cuda is different as the way they are included;
- [ ] Different include guarding used for CUDA enablement (same is true for ROCM and Vulkan)

I'm not yet able to build XLA in OSS, so testing was limited here.

### CODE REVIEW

**Comment by gbaned** [comment]
Hi @jpienaar This PR is in draft, any update on this? Please. Thank you!

**Comment by gbaned** [comment]
Hi @jpienaar This PR is in draft, any update on this? Please. Thank you!

**Comment by kamaljeeti** [comment]
Hi @jpienaar,
Any update on this PR? Please. Thank you!

**Comment by jpienaar** [comment]
Correct, this was just a draft to show what would be needed. No intention to pursue in short term.

**Pull request closed without merging**
