### PR TITLE
[ROCm] Fixing move constructor: make sure 'shape' is properly initialized for 'other'

### PR DESCRIPTION
**Pull request by pemeliya**
The move ctor of class Literal is implemented in terms of the move operator which swaps shapes of two objects leaving the shape of 'other' object unitialized. As a result accessing other.shape() leads to segmentation fault. The crash was initially observed in xla::HloInstruction::ToString() when the logging level is set to 3, after the call to LayoutNormalizationVisitor::HandleConstant(xla::HloInstruction*) which uses the move constructor of Literal.
This fix properly initializes literal's shape before calling the move operator.

Hi @akuegel : can you please review it ?

### CODE REVIEW

**Comment by radhakrishnaba** [comment]
Hi pemeliya, can you sign up on this CLA provided below. 
https://cla.developers.google.com/clas

**Review by akuegel — CHANGES_REQUESTED** [review]
Thanks for your PR, and for describing the issue with the use after move.
I think I have an idea for a better fix:
The CreateConstant call here could be changed to another version of CreateConstant that takes the shape normalized_shape as another parameter:

https://github.com/openxla/xla/blob/8235b2ddbb2b4362128bdf6b4d6d13c384eaa190/xla/service/layout_normalization.cc#L72

This additional variant of CreateConstant needs to be added, and that can call the (currently unused) constructor here:

https://github.com/openxla/xla/blob/8235b2ddbb2b4362128bdf6b4d6d13c384eaa190/xla/hlo/ir/hlo_instructions.h#L1157

**Comment by akuegel** [comment]
> Thanks for your PR, and for describing the issue with the use after move. I think I have an idea for a better fix: The CreateConstant call here could be changed to another version of CreateConstant that takes the shape normalized_shape as another parameter:
> 
> https://github.com/openxla/xla/blob/8235b2ddbb2b4362128bdf6b4d6d13c384eaa190/xla/service/layout_normalization.cc#L72
> 
> This additional variant of CreateConstant needs to be added, and that can call the (currently unused) constructor here:
> 
> https://github.com/openxla/xla/blob/8235b2ddbb2b4362128bdf6b4d6d13c384eaa190/xla/hlo/ir/hlo_instructions.h#L1157

Actually I just realized this would also be a problem, because the Shape only lives inside HandleConstant.
But you can just set the shape of the new constant:

```
*normalized->mutable_shape() = normalized_shape.
```

**Comment by pemeliya** [comment]
I think I undertand your point: in that way we have one less call to the "unwanted" function Literal::mutable_shape_do_not_use().

I have added an overload function HloInstruction::CreateConstant() which takes shape as a second parameter, now it looks as follows:
`    
Shape normalized_shape = Normalize(hlo->shape());
 //*literal.mutable_shape_do_not_use() = normalized_shape;

HloInstruction* normalized = hlo->parent()->AddInstruction(
        HloInstruction::CreateConstant(std::move(literal), normalized_shape), &hlo->metadata());
`
But we still need to do something with the 'moved-from' object 'hlo' whose 'hlo->literal()->shape()' 
is not properly set yet.

**Comment by akuegel** [comment]
> I think I undertand your point: in that way we have one less call to the "unwanted" function Literal::mutable_shape_do_not_use().
> 
> I have added an overload function HloInstruction::CreateConstant() which takes shape as a second parameter, now it looks as follows: ` Shape normalized_shape = Normalize(hlo->shape()); //*literal.mutable_shape_do_not_use() = normalized_shape;
> 
> HloInstruction* normalized = hlo->parent()->AddInstruction( HloInstruction::CreateConstant(std::move(literal), normalized_shape), &hlo->metadata()); ` But we still need to do something with the 'moved-from' object 'hlo' whose 'hlo->literal()->shape()' is not properly set yet.

Yes, you are right, the actual problem is not with the new constant, but with the old constant. I am still thinking about how to best address this, but essentially if I understand your fix correctly, it would just make sure that the old constant will have an empty shape. Ideally we would still want to show the original shape in the log. So my latest suggestion (but I haven't tried it) is to keep track of the original shape (so not using const reference) and then assign it 'hlo' again after CreateConstant was called (which would have replaced the shape with uninitialized shape). Here, it would not matter that the shape only lives inside HandleConstant, because after HandleConstant, the original 'hlo' instruction is gone.

**Comment by akuegel** [comment]
Also, please let me know if I should just try to fix this myself, or if you want to fix it yourself. So I guess I would be ok with your fix as a temporary fix, but would then try to followup with a fix that makes sure we log the right shape for the old instruction.

**Comment by pemeliya** [comment]
yes, exactly, with my fix, the old instruction will have an empty shape (NilShape). I have tried to figure out how to keep the old shape of 'hlo' available but only the following version works for me:

```
    Literal& literal = *Cast<HloConstantInstruction>(hlo)->mutable_literal();
    const Shape& shape = hlo->shape();
    if (literal.shape().IsTuple()) {
      // TODO(cheshire): Tuple constants.
      return OkStatus();
    }
    Shape normalized_shape = Normalize(hlo->shape());
    
    HloInstruction* normalized = hlo->parent()->AddInstruction(
        HloInstruction::CreateConstant(std::move(literal), normalized_shape), &hlo->metadata());

    literal = Literal(normalized_shape, true); // this allocated memory for literal !
    VLOG(3) << "old: " << hlo->ToString() << " replace with: " << normalized->ToString();
```
This, however, allocated memory for literal, which is what we want to avoid I guess.. Perhaps, there is some tricky way to use BorrowingLiteral here (which has a common LiteralBase class with Literal) ? But I couldn't figure out it now.. 
So, perhaps you can have a look at it yourself ? And my fix is just to make sure that 'moved-from' object is "in a valid but unspecified state"..

**Review by akuegel — APPROVED** [review]

**Comment by pemeliya** [comment]
I think I unterstand it more or less now; even if we do it as follows:

```
    Literal& literal = *Cast<HloConstantInstruction>(hlo)->mutable_literal();
    Shape shape = hlo->shape(); // <------ keep the old shape !
    if (literal.shape().IsTuple()) {
      // TODO(cheshire): Tuple constants.
      return OkStatus();
    }
    Shape normalized_shape = Normalize(shape);
    HloInstruction* normalized = hlo->parent()->AddInstruction(
        HloInstruction::CreateConstant(std::move(literal), normalized_shape), &hlo->metadata());

    *hlo->mutable_shape() = shape; // <---- restore the old shape
```
calling 
```
VLOG(3) << hlo->ToString();
```
would still crash because 

hlo->shape() and hlo->literal().shape() 

are just two different things: one is stored inside HloInstruction directly and the other one inside HloConstantInstruction::Literal. So, we need to reassign literal's shape which is only possible if the literal is properly allocated..

**Comment by akuegel** [comment]
> I think I unterstand it more or less now; even if we do it as follows:
> 
> ```
>     Literal& literal = *Cast<HloConstantInstruction>(hlo)->mutable_literal();
>     Shape shape = hlo->shape(); // <------ keep the old shape !
>     if (literal.shape().IsTuple()) {
>       // TODO(cheshire): Tuple constants.
>       return OkStatus();
>     }
>     Shape normalized_shape = Normalize(shape);
>     HloInstruction* normalized = hlo->parent()->AddInstruction(
>         HloInstruction::CreateConstant(std::move(literal), normalized_shape), &hlo->metadata());
> 
>     *hlo->mutable_shape() = shape; // <---- restore the old shape
> ```
> 
> calling
> 
> ```
> VLOG(3) << hlo->ToString();
> ```
> 
> would still crash because
> 
> hlo->shape() and hlo->literal().shape()
> 
> are just two different things: one is stored inside HloInstruction directly and the other one inside HloConstantInstruction::Literal. So, we need to reassign literal's shape which is only possible if the literal is properly allocated..

Interesting. I thought that VLOG(3) << hlo->ToString() would just use the shape assigned to HloInstruction, not the shape from the literal. When looking at the code, I couldn't find the access to literal()->shape() in printing code. I guess I will have to debug this a bit myself when I find the time.

**Comment by pemeliya** [comment]
yes.. it took me some time to figure it out: HloConstantInstruction overrides
```
  void PrintOperandsWithCanonicalNameMap(
      Printer* printer, const HloPrintOptions& options,
      CanonicalNameMap* canonical_name_map) const override;
```
which gets called during HloInstruction::ToString()

**Comment by akuegel** [comment]
> 

Yes, but by default, this should just print "{...}" and not go into the blocks where the literal shape is accessed. print_only_essential_constants and print_large_constants are set to false by default.

**Comment by pemeliya** [comment]
That's right, the point, the protected member '_literal' is not NULL after "moving-from" but its Literal::shape() is NULL.
That is why, it crashed at the following place inside HloConstantInstruction::PrintOperandsWithCanonicalNameMap():

```
  if (literal_ &&
      ((shape().IsArray() && ShapeUtil::ElementsIn(shape()) <= 10) ||
       options.print_large_constants())) {
     // Literal::ToString emits multidimensional arrays over multiple
    // lines. Compact this into one line by stripping out white space.
    literal_->PrintWithoutShapeOneline(printer);  // <-------------------- CRASH happens here
  } else {
    // Do not show large constants or tuples.
    printer->Append("{...}");
  }
```
And my fix just assigned 'NilShape()' to this '_literal' member variable.

**Comment by pemeliya** [comment]
@akuegel : I have decided to commit your suggestions as well because they make total sense. Otherwise, I am going for vacations tomorrow, and this issue will be easily forgotten..

So, basically, I have added  an overloaded function 'HloInstruction::CreateConstant()' which takes 'shape' as a second parameter and then internally calls: 
```
HloConstantInstruction(Literal literal, const Shape& shape); 
```
This way, we can effectively avoid the call to unwanted function Literal::mutable_shape_do_not_use().

**Comment by akuegel** [comment]
After thinking about this a bit more, I think I found a good solution. It still calls mutable_shape_do_not_use() but otherwise it simplifies the code a lot. And since we keep the old constant instruction and the old literal, there is absolutely no risk of use after move.

```
    Shape shape = hlo->shape();
    Shape normalized_shape = Normalize(shape);
    *literal.mutable_shape_do_not_use() = normalized_shape;
    *hlo->mutable_shape() = normalized_shape;
    HloInstruction* bc_to_orig = MakeBitcastHlo(hlo, shape);
    return hlo->ReplaceAllUsesWithDifferentShape(bc_to_orig);
```

I will land this change, so this PR will become obsolete. Thanks a lot for finding this bug and for the fruitful discussion :)

**Comment by akuegel** [comment]
I have landed my fix in https://github.com/openxla/xla/commit/2840f4f35c94d416fa7c0506faa65c6c322711bf
It actually uncovered another problem: we were revisiting already normalized ops, which caused a problem when no new constant was created. So now with the fix, that part should be more efficient, as we do not needlessly try to normalize again.

**Pull request closed without merging**
