### PR TITLE
[XLA:GPU] Upgrade cuDNN frontend to 1.5

### PR DESCRIPTION
**Pull request by Cjkkkk**
release note: https://github.com/NVIDIA/cudnn-frontend/releases/tag/v1.5.0

### CODE REVIEW

**Comment by cheshire** [comment]
@hawkinsp @beckerhe are we good to go?

**Comment by Cjkkkk** [comment]
Hi, anything pending for this?

**Comment by beckerhe** [comment]
> Hi, anything pending for this?

There seem to be some build errors:

```
ERROR: /[github/xla/xla/service/gpu/BUILD:3007](https://cs.corp.google.com/piper///depot/google3/github/xla/xla/service/gpu/BUILD?l=3007&cl=643366237):11: Compiling xla/service/gpu/cudnn_workspace_rewriter.cc failed: (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command (from target //xla/service/gpu:cudnn_workspace_rewriter) external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/k8-opt/bin/xla/service/gpu/_objs/cudnn_workspace_rewriter/cudnn_workspace_rewriter.d ... (remaining 366 arguments skipped)
In file included from [xla/service/gpu/cudnn_workspace_rewriter.cc:43](https://cs.corp.google.com/piper///depot/google3/xla/service/gpu/cudnn_workspace_rewriter.cc?l=43&cl=643366237):
In file included from [./xla/stream_executor/cuda/cuda_dnn.h:40](https://cs.corp.google.com/piper///depot/google3/xla/stream_executor/cuda/cuda_dnn.h?l=40&cl=643366237):
In file included from [bazel-out/k8-opt/bin/external/cudnn_frontend_archive/_virtual_includes/cudnn_frontend/third_party/cudnn_frontend/include/cudnn_frontend.h:123](https://cs.corp.google.com/piper///depot/google3/bazel-out/k8-opt/bin/external/cudnn_frontend_archive/_virtual_includes/cudnn_frontend/third_party/cudnn_frontend/include/cudnn_frontend.h?l=123&cl=643366237):
In file included from [bazel-out/k8-opt/bin/external/cudnn_frontend_archive/_virtual_includes/cudnn_frontend/third_party/cudnn_frontend/include/cudnn_frontend/graph_interface.h:5](https://cs.corp.google.com/piper///depot/google3/bazel-out/k8-opt/bin/external/cudnn_frontend_archive/_virtual_includes/cudnn_frontend/third_party/cudnn_frontend/include/cudnn_frontend/graph_interface.h?l=5&cl=643366237):
In file included from [bazel-out/k8-opt/bin/external/cudnn_frontend_archive/_virtual_includes/cudnn_frontend/third_party/cudnn_frontend/include/cudnn_frontend/node/batchnorm.h:7](https://cs.corp.google.com/piper///depot/google3/bazel-out/k8-opt/bin/external/cudnn_frontend_archive/_virtual_includes/cudnn_frontend/third_party/cudnn_frontend/include/cudnn_frontend/node/batchnorm.h?l=7&cl=643366237):
In file included from [bazel-out/k8-opt/bin/external/cudnn_frontend_archive/_virtual_includes/cudnn_frontend/third_party/cudnn_frontend/include/cudnn_frontend/node/../node_interface.h:19](https://cs.corp.google.com/piper///depot/google3/bazel-out/k8-opt/bin/external/cudnn_frontend_archive/_virtual_includes/cudnn_frontend/third_party/cudnn_frontend/include/cudnn_frontend/node_interface.h?l=19&cl=643366237):
In file included from [bazel-out/k8-opt/bin/external/cudnn_frontend_archive/_virtual_includes/cudnn_frontend/third_party/cudnn_frontend/include/cudnn_frontend/node/../cudnn_interface.h:16](https://cs.corp.google.com/piper///depot/google3/bazel-out/k8-opt/bin/external/cudnn_frontend_archive/_virtual_includes/cudnn_frontend/third_party/cudnn_frontend/include/cudnn_frontend/cudnn_interface.h?l=16&cl=643366237):
In file included from [bazel-out/k8-opt/bin/external/cudnn_frontend_archive/_virtual_includes/cudnn_frontend/third_party/cudnn_frontend/include/cudnn_frontend/node/../plans.h:11](https://cs.corp.google.com/piper///depot/google3/bazel-out/k8-opt/bin/external/cudnn_frontend_archive/_virtual_includes/cudnn_frontend/third_party/cudnn_frontend/include/cudnn_frontend/plans.h?l=11&cl=643366237):
[bazel-out/k8-opt/bin/external/cudnn_frontend_archive/_virtual_includes/cudnn_frontend/third_party/cudnn_frontend/include/cudnn_frontend/node/../backend/execution_helpers.h:5](https://cs.corp.google.com/piper///depot/google3/bazel-out/k8-opt/bin/external/cudnn_frontend_archive/_virtual_includes/cudnn_frontend/third_party/cudnn_frontend/include/cudnn_frontend/backend/execution_helpers.h?l=5&cl=643366237):10: fatal error: 'cudnn.h' file not found
    5 | #include "cudnn.h"
      |          ^~~~~~~~~
```

Looks related to the update.

**Comment by Cjkkkk** [comment]
I replaced `#include "cudnn.h"` with `#include "third_party/gpus/cudnn/cudnn.h"`, which should fix the issue.

**Review by beckerhe — APPROVED** [review]

**Review by NaiyerRizz — APPROVED** [review]

**Pull request closed without merging**
