### PR TITLE
[ROCm] Fix transpose related tests which breaks due to 6fabf59

### PR DESCRIPTION
**Pull request by hsharsha**
Failure is due to https://github.com/openxla/xla/pull/16336

### CODE REVIEW

**Comment by mooskagh** [comment]
How exactly is `CompileAndVerifyIr` failing? Maybe it makes sense to replace the check with something else rather than removing it?

**Comment by hsharsha** [comment]
> How exactly is `CompileAndVerifyIr` failing? Maybe it makes sense to replace the check with something else rather than removing it?

It is not getting this string `call void BARRIER()`
It was removed in older tests at https://github.com/openxla/xla/pull/16336/files#diff-8874213f2bac0a0c682b006a9990a5a49aff4eecff481f074782692633e55c70L218-L224. Hence I removed them

**Review by akuegel — CHANGES_REQUESTED** [review]
I think this is the wrong fix. You only see those differences because ROCM doesn't have the new MLIR emitters enabled by default. If we change the test expectations, it will fail on Nvidia GPUs where it is enabled by default.
Maybe disable the tests for now on ROCM, until the mlir emitters are enabled there as well?

**Comment by hsharsha** [comment]
Test works after [fbd00d9](https://github.com/openxla/xla/commit/fbd00d9b94ba9fd155b5fca572122c55f691424f)

**Comment by akuegel** [comment]
Thanks for the confirmation, happy that they work again! And sorry for temporarily breaking them.

**Pull request closed without merging**
