### PR TITLE
Remove the conditions that break auto-pgle workflow.

### PR DESCRIPTION
**Pull request by shraiysh**
These conditions seem to break the auto-pgle workflow. Removing them.

### CODE REVIEW

**Review by golechwierowicz — CHANGES_REQUESTED** [review]
If it wasn't caught by existing unit tests please write one.

**Comment by golechwierowicz** [comment]
Actually the logic from

https://github.com/openxla/xla/pull/18763/files#diff-a8f2059ceccdcae2df273d8bc78620741292cc6df9a71ba875e55101adaff817R460-R466

breaks AutoPGLE workflow where all of the runs have the same flag set. I think it's best to remove all of those ifs.

https://github.com/openxla/xla/pull/18763/files#diff-a8f2059ceccdcae2df273d8bc78620741292cc6df9a71ba875e55101adaff817R460-R475

**Review by golechwierowicz — APPROVED** [review]

**Comment by shraiysh** [comment]
I see an internal failure @golechwierowicz . Is this because we are missing a test? I can add one that just checks that this combination of options does not raise an error. Let me know.

**Comment by golechwierowicz** [comment]
Failure is here: https://btx.cloud.google.com/invocations/5b9717eb-ae61-4957-b01f-29ed83fa797b/targets/tensorflow%2Fxla%2Fjax%2Fgpu%2Fbuild_gpu/log. Looks it's coming from JAX and seems unrelated. Can you rebase the PR?

**Comment by shraiysh** [comment]
> Can you rebase the PR?

Done

**Review by golechwierowicz — APPROVED** [review]

**Pull request closed without merging**
