### PR TITLE
[ROCm] Fix build break with gcc due to `53417984`

### PR DESCRIPTION
**Pull request by hsharsha**
@majnemer This fixes build break on gcc due to https://github.com/openxla/xla/commit/53417984a9baf80ac9b677f13e628867298f8eae

### CODE REVIEW

**Comment by mooskagh** [comment]
What was the error without that fix?

Actually, the member functions defined within the class, are inline automatically.

**Comment by hsharsha** [comment]
This is the error 
```
./xla/service/gpu/ir_emission_utils.h: In function ‘constexpr int64_t xla::gpu::WarpSize(const stream_executor::DeviceDescription&)’:
./xla/service/gpu/ir_emission_utils.h:69:42: error: call to non-‘constexpr’ function ‘const int64_t& stream_executor::DeviceDescription::threads_per_warp() const’
   69 |   return gpu_device_info.threads_per_warp();
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
In file included from ./xla/stream_executor/platform.h:27,
                 from ./xla/service/computation_placer.h:29,
                 from ./xla/service/hlo_module_config.h:34,
                 from ./xla/hlo/ir/hlo_module.h:51,
                 from ./xla/hlo/analysis/hlo_dataflow_analysis.h:40,
                 from ./xla/hlo/analysis/hlo_alias_analysis.h:27,
                 from ./xla/service/buffer_assignment.h:36,
                 from ./xla/service/gpu/ir_emission_utils.h:37,
                 from ./xla/service/gpu/hlo_fusion_analysis.h:30,
                 from ./xla/service/gpu/model/fusion_analysis_cache.h:26,
                 from xla/service/gpu/model/fusion_analysis_cache.cc:16:
./xla/stream_executor/device_description.h:345:18: note: ‘const int64_t& stream_executor::DeviceDescription::threads_per_warp() const’ declared here
  345 |   const int64_t &threads_per_warp() const { return threads_per_warp_; }
      |                  ^~~~~~~~~~~~~~~~
```

**Comment by hsharsha** [comment]
Addressed review comment in https://github.com/openxla/xla/pull/19925/commits/d5e67855886877638d7bf166f914ed8117b4185a

**Review by mooskagh — APPROVED** [review]

**Comment by majnemer** [comment]
It seems to me that we should instead remove the `constexpr` from the `WarpSize` function in ir_emission_utils.h as it is unlikely to ever be meaningfully constexpr.

**Comment by hsharsha** [comment]
@majnemer https://github.com/openxla/xla/commit/53417984a9baf80ac9b677f13e628867298f8eae had 75 files changed. My bad I did not go through the PR and assumed there could be multiple palaces where this function would be defined. like in other emitters like triton etc... and ended up modifying device_description.h file.

**Pull request closed without merging**
