### PR TITLE
Add new ISAs

### PR DESCRIPTION
**Pull request by gaurides**
This PR is for ISA related changes in XLA part. Earlier they were part of this PR - https://github.com/tensorflow/tensorflow/pull/62084

### CODE REVIEW

**Comment by cheshire** [comment]
Looks good to me, but @ezhulenev , @d0k or @penpornk should probably take a look.

**Review by penpornk — APPROVED** [review]
Looks good to me. Thank you for the PR!

**Review by ezhulenev — APPROVED** [review]

**Review by cantonios — APPROVED** [review]

**Comment by gaurides** [comment]
Hi @penpornk - the [tsl ](https://github.com/google/tsl repo shows it doesn't accept any PRs or issues. Is it still valid? How do i submit PR? Also, want to confirm the test process.
"Warning This repo is currently being migrated from TensorFlow. Until the migration is complete, this repo will not be accepting PRs or issues. "

**Comment by penpornk** [comment]
@gaurides You're right. I just checked with the team. TSL won't accept PRs. Sorry about that! I'll just pull in an empty import and manually add changes there. The merge should still be attributed to this PR that way.

**On JAX & XLA Linux GPU CI failures:** 
I think both are unrelated to this PR. We aren't modifying any build rule so I'm not sure where `tensorflow/core/platform` comes from.
[XLA Linux GPU](https://btx-internal.corp.google.com/invocations/49fe0005-2029-44c8-a6f4-f4e37e16ba0b/targets/tensorflow%2Fxla%2Flinux%2Fgpu%2Fbuild_gpu/log)
```
ERROR: /tf/xla/xla/service/gpu/BUILD:2859:11: no such package 'tensorflow/core/platform': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /tf/xla/tensorflow/core/platform and referenced by '//xla/service/gpu:gpu_compiler'
```
[JAX Linux GPU](https://btx-internal.corp.google.com/invocations/c45ee870-4229-4fa0-ba18-e0e599c5e571/targets/tensorflow%2Fxla%2Fjax%2Fgpu%2Fbuild_gpu/log)
```
ERROR: /tmpfs/bazel_output/_bazel_kbuilder/1669de3e80cb98acba4a615c5fafcf1d/external/xla/xla/service/gpu/BUILD:2859:11: no such package '@xla//tensorflow/core/platform': BUILD file not found in directory 'tensorflow/core/platform' of external repository @xla. Add a BUILD file to a directory to mark it as a package. and referenced by '@xla//xla/service/gpu:gpu_compiler'
```

**Comment by gaurides** [comment]
Thanks @penpornk . I will remove these files from the Tensorflow PR.

**Pull request closed without merging**
