### PR TITLE
[ROCM] gemm_rewriter: bugfixing supported datatypes combinations

### PR DESCRIPTION
**Pull request by pemeliya**
This PR https://github.com/openxla/xla/pull/12553 introduced some a regression bug by enabling CUDA-specific and ROCM-specific datatype combinations on both platforms.

@xla-rotation: could you please have a look ?

### CODE REVIEW

**Review by golechwierowicz — APPROVED** [review]

**Comment by golechwierowicz** [comment]
Can you write a test so the regression does not happen in the future?

**Comment by pemeliya** [comment]
> Can you write a test so the regression does not happen in the future?

Yes, actually we found it out by //xla/tests/dot_operation_test failures on ROCM however this test is not included in AMD community build due to long running times. I will try to extend some of the existing AMD community tests to include this one.

**Comment by golechwierowicz** [comment]
Can we first add a test to AMD CI build and add a unit test in gemm_rewriter_test.cc to cover this path?

**Comment by pemeliya** [comment]
> Can we first add a test to AMD CI build and add a unit test in gemm_rewriter_test.cc to cover this path?

Yes, I have added a subtest to matmul_test which is a part of AMD CI and verified that it fails without my fix. And also added gemm_rewriter subtest to check for f64/c64 dots (which are not supported by hipblas-lt yet and hence shall be rewritten to legacy rocblas calls)

**Review by golechwierowicz — APPROVED** [review]

**Pull request closed without merging**
