### PR TITLE
Add OUTPUT_PATH environment for housing generated whl file

### PR DESCRIPTION
**Pull request by hsharsha**

### CODE REVIEW

**Comment by hsharsha** [comment]
@ddunl Please see if we can accommodate this.

**Comment by ddunl** [comment]
To clarify - does this fix when building with TF or JAX? I think I'm not completely understanding the motivation

**Comment by hsharsha** [comment]
> To clarify - does this fix when building with TF or JAX? I think I'm not completely understanding the motivation

This is to build with TF so that we can house tf wheel packages in the directory listed with OUTPUT_PATH which can be passed to bazel using repo_env

**Comment by ddunl** [comment]
Gotcha, @vam-google does this look good to you?

**Review by vam-google — COMMENTED** [review]
This PR adds OUTPUT_PATH env variable to the corresponding repository rule, but does not use it in any way, so this PR as is should be a no-op. If that OUTPUT_PATH env variable is expected to be propagated/consumed somehow indirectly (i.e. basically magically) please explain how it is supposed to work, as as of now it seems no-op.

**Comment by hsharsha** [comment]
> This PR adds OUTPUT_PATH env variable to the corresponding repository rule, but does not use it in any way, so this PR as is should be a no-op. If that OUTPUT_PATH env variable is expected to be propagated/consumed somehow indirectly (i.e. basically magically) please explain how it is supposed to work, as as of now it seems no-op.

I had a long standing PR at https://github.com/tensorflow/tensorflow/pull/66633
where tensorflow/tools/pip_package/utils/tf_wheel.bzl will consume OUTPUT_PATH variable and pass it onto setup.py to build wheel file.

Now with latest tensorflow python_repo.bzl is coming from XLA instead of tensorflow hence the corresponding change in XLA.

**Comment by vam-google** [comment]
@hsharsha Please check my comment in TF's repo for that PR. IIUC, unfortunately your prs are trying to do what we explicitly forbid to do.

**Comment by ddunl** [comment]
I'm closing for now based on the comment from @vam-google but feel free to reopen if anything is unclear

**Pull request closed without merging**
