### PR TITLE
[ROCm] Triton in XLA for ROCm - gemm rewriter triton related changes.

### PR DESCRIPTION
**Pull request by zoranjovanovic-ns**
First commit of the series for enabling Triton in XLA for ROCm .

### CODE REVIEW

**Review by tdanyluk — APPROVED** [review]
This looks good to me, thank you.

**Comment by i-chaochen** [comment]
@tdanyluk we notice there is a conflict, but there is a PR from copybara-service to merge now. We wonder shall we resolve this conflict and rebase it again? which I think might need you to approve again?

**Comment by cheshire** [comment]
Yes, could you re-base and I'll re-approve?

**Comment by zoranjovanovic-ns** [comment]
> Yes, could you re-base and I'll re-approve?

@cheshire rebased and pushed.

**Review by cheshire — APPROVED** [review]

**Comment by zoranjovanovic-ns** [comment]
@cheshire Do you know what is blocking PR from being merged?

**Comment by tdanyluk** [comment]
There are some internal failures, but nothing major, I'm trying to submit it.

**Pull request closed without merging**
