### PR TITLE
[ROCM] Implementing GemmBlasWithAlgorithm BLAS API routines v2

### PR DESCRIPTION
**Pull request by pemeliya**
This was extracted from a large unmerged PR: https://github.com/openxla/xla/pull/7782

Here we enable BLAS-with-algorithm functionality and, as a consequence, also enable several gemm-related tests on ROCM platform. BLAS API functions implemented:

- DoBlasGemmWithAlgorithm
- DoBlasGemmStridedBatchedWithAlgorithm
- GetBlasGemmAlgorithms 

The main difficulty was the implementation of GetBlasGemmAlgorithms. Unlike a CUDA side, where the set of algorithms is static, rocBLAS provides rouines **rocblas_gemm_ex_get_solutions** or **rocblas_gemm_strided_batched_ex_get_solutions**
which requires a **full set** of GEMM parameters to retrieve feasible solutions.

Therefore, I had to adjust BlasSupport interface for **GetBlasGemmAlgorithms** function. As a preparation for this, we also added MatrixDescriptors in this PR: https://github.com/openxla/xla/pull/7820 (to avoid code duplication) since GetBlasGemmAlgorithms basically require the same arguments as RunGemm() from matmul_utils.cc.  Note that, CUDA blas implementation is almost not touched - I have only changed the interface of  GetBlasGemmAlgorithms function where the most arguments are unused on CUDA.

@xla-rotation: could you please have a look ?

### CODE REVIEW

**Comment by i-chaochen** [comment]
@xla-rotation could you have a check on this PR, please. Thanks!

**Comment by kamaljeeti** [comment]
Hi @ezhulenev , can you look into this once? Thanks.

**Comment by pemeliya** [comment]
Let me know if this PR is still too big ? I can split it up again into NFC and feature parts..

**Review by ezhulenev — APPROVED** [review]

**Comment by i-chaochen** [comment]
Hi @ddunl 

JAX Linux CPU CI somehow is broken in this PR and nothing related to our changes...

```
2024/01/31 14:10:05 could not download Bazel: could not copy from https://releases.bazel.build/7.0.2/release/bazel-7.0.2-linux-x86_64 to /home/kbuilder/.cache/bazelisk/bin/bazelbuild/download263886975: stream error: stream ID 1; INTERNAL_ERROR
```

And this PR is approval, wonder is any other changes we should do to get it merged?

Thanks!

**Comment by ddunl** [comment]
I think it's just a flake, it should still merge ok given the internal tests pass

**Pull request closed without merging**
