### PR TITLE
Add select(a, true, false) and select(a, false, true) cases to algebraic_simplifier

### PR DESCRIPTION
**Pull request by apivovarov**
This PR adds the following cases for [select](https://www.tensorflow.org/xla/operation_semantics#select) op to algebraic_simplifier:
```
If all "select" arguments of type PRED:

select(a, true, false) -> a
select(a, false, true) -> not(a)
```
@lipracer Can you review it?

### CODE REVIEW

**Comment by lipracer** [comment]
Thanks,It’s LGTM.but I am not the member of xla.

**Review by lipracer — APPROVED** [review]

**Review by yingweiz — APPROVED** [review]

**Comment by lipracer** [comment]
@jpienaar Can you help to review this PR?

**Comment by apivovarov** [comment]
@majnemer Can you review this PR too? it is another optimization in algebraic_simplifier (Related PR https://github.com/openxla/xla/pull/6601)

**Review by akuegel — APPROVED** [review]

**Comment by apivovarov** [comment]
@ddunl @cheshire This PR already got approval from one of the member of OpenXLA. I want to double check if more reviews are needed? Regarding the tests - only feedback/copybara - Google internal checks FAILED.

**Comment by ddunl** [comment]
From what I can tell all the internal failures are flaky, should get merged soon. If I see a failures later today that look legitimate I'll let you know. Thanks for the PR!!!

**Pull request closed without merging**
