### PR TITLE
[ROCM] fixing build brake 23/12/21

### PR DESCRIPTION
**Pull request by pemeliya**
This is a ongoing build brake fix for ROCM due to recent changes in gpu_runtime.h

@xla-rotation: could you check this, please ?

### CODE REVIEW

**Comment by ddunl** [comment]
This has conflicts so I think needs rebase. On an unrelated note, would you mind submitting a PR to fix the buildifier linter? There should be a docstring in the rocm `build_defs.bzl`.

**Comment by pemeliya** [comment]
yes, sure, I am going to look at it know.. sorry for delay

**Comment by pemeliya** [comment]
@ddunl I have tried to fix buildifier warning but still not able to figure out what is it complaining about ? Can you check it please ?

**Comment by kamaljeeti** [comment]
Hi @ddunl , can you look into this once? Thanks.

**Comment by akuegel** [comment]
> @ddunl I have tried to fix buildifier warning but still not able to figure out what is it complaining about ? Can you check it please ?

I think the buildifier warning was fixed in https://github.com/openxla/xla/pull/8075

**Review by akuegel — APPROVED** [review]

**Comment by akuegel** [comment]
It seems you will also need to update //xla/service/gpu:nvptx_compiler_test

**Review by akuegel — APPROVED** [review]

**Pull request closed without merging**
