### PR TITLE
[ROCm] Enable GpuCommandBuffer::Trace

### PR DESCRIPTION
**Pull request by draganmladjenovic**

### CODE REVIEW

**Comment by i-chaochen** [comment]
Hi @xla-rotation could you please help us to review. Thanks in advance!

**Comment by draganmladjenovic** [comment]
@ezhulenev gentle ping.

**Comment by ddunl** [comment]
Sorry about that, I tagged Eugene last time but he's on vacation, can you review @anlunx ?

**Review by anlunx — APPROVED** [review]
LGTM

**Review by ddunl — APPROVED** [review]

**Comment by kamaljeeti** [comment]
Hi @ddunl , there are couple of checks failed on the Clang and Cl. Can you have a look at them once? Thanks.

**Pull request closed without merging**
