### PR TITLE
[XLA:GPU] Upgrade cuDNN frontend to v1.1.0.

### PR DESCRIPTION
**Pull request by sergachev**

### CODE REVIEW

**Comment by reedwm** [comment]
@chsigg @dimitar-asenov I can't remember, do we have to update cuDNN frontend internally at the same time? (Or perhaps @sergachev you might remember?)

**Comment by sergachev** [comment]
> @chsigg @dimitar-asenov I can't remember, do we have to update cuDNN frontend internally at the same time? (Or perhaps @sergachev you might remember?)

I don't know unfortunately, can just point at the previous version bump: https://github.com/openxla/xla/commit/d58d3ee55ccaf10a1fc0cc9d2f134e0f3c9bf5f3

**Comment by chsigg** [comment]
I would say it's good to keep them in sync, yes.

**Comment by dimitar-asenov** [comment]
I have started updating the internal code to v1.1.0. Once that's done, we can submit this PR as well.

**Comment by dimitar-asenov** [comment]
This can now be merged.

**Review by dimitar-asenov — APPROVED** [review]
OK to merge.

**Review by tdanyluk — APPROVED** [review]
Approving based on dimitar-asenov's feedback

**Pull request closed without merging**
