### PR TITLE
Fix build issue in xla/ffi XLA_FFI_REGISTER_ENUM_ATTR_DECODING

### PR DESCRIPTION
**Pull request by apivovarov**
Currently gcc11 shows the following build error:
```bash
./xla/ffi/api/api.h:1640:38: error: global qualification of class name is invalid before '{' token
 1640 |   struct ::xla::ffi::AttrDecoding<T> {                                        \
      |                                      ^
xla/ffi/api/ffi_test.cc:59:1: note: in expansion of macro 'XLA_FFI_REGISTER_ENUM_ATTR_DECODING'
   59 | XLA_FFI_REGISTER_ENUM_ATTR_DECODING(::xla::ffi::Int32BasedEnum);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

This PR fixes it.

### CODE REVIEW

**Review by dimitar-asenov — APPROVED** [review]
Thanks for this, I will patch this internally, as the proposed solution doesn't work when calling the macro outside of the `xla::ffi` namespace.

**Comment by dimitar-asenov** [comment]
@apivovarov The fix is submitted. It differs from your original one, can you please double-check that it works?

**Comment by apivovarov** [comment]
> @apivovarov The fix is submitted. It differs from your original one, can you please double-check that it works?

Hi @dimitar-asenov , sure!
- The fix [a3393f5](https://github.com/openxla/xla/commit/a3393f508626ddf2c1772b1db3a5d58f45ce4752) works fine.

Thank you!

**Comment by apivovarov** [comment]
XLA_FFI_REGISTER_STRUCT_ATTR_DECODING  and XLA_FFI_REGISTER_ENUM_ATTR_DECODING  macros were reverted back to use `::xla::ffi::` in https://github.com/openxla/xla/commit/ef49d057bffd4b8ff14bda925d48ea7610aaa856

This change causes a compilation error when using GCC.

@dimitar-asenov @dfm

**Pull request closed without merging**
