### PR TITLE
[Replacement for #7484] [XLA:CPU] [oneDNN] Adding support for MatMul + BiasAdd fusion with oneDNN custom call rewrite

### PR DESCRIPTION
**Pull request by mahmoud-abuzaina**
This PR enables OneDNN library call for the matched XLA HLO MatMul + BiasAdd patterns through custom_call instruction. In particular, this PR:

1. Renames oneDNN matmul rewriter pass and moves it after layout assignment pass.
2. Enables transposed input support for oneDNN matmul
3. Enables MatMul + BiasAdd pattern matching with oneDNN rewrite
4. Adds multiple tests with different variations of MatMul + BiasAdd pattern

Original Tensorflow PR: https://github.com/tensorflow/tensorflow/pull/62243
With contribution from @akhilgoe

### CODE REVIEW

**Review by penpornk — APPROVED** [review]
Thank you for the PR!

**Comment by penpornk** [comment]
@mahmoud-abuzaina Could you please help resolve conflicts?

**Comment by mahmoud-abuzaina** [comment]
@penpornk Thank you for approving the PR. I have resolved the merge conflicts.

**Review by penpornk — APPROVED** [review]
Thank you!

**Pull request closed without merging**
