### PR TITLE
[NVIDIA] Bump up cudnn frontend to v1.0

### PR DESCRIPTION
**Pull request by kaixih**
This pull request updates the cuDNN frontend to [the latest version 1.0](https://github.com/NVIDIA/cudnn-frontend/releases/tag/v1.0.0).

### CODE REVIEW

**Comment by radhakrishnaba** [comment]
Hi @cheshire, can you look into this once? Thanks.

**Comment by akuegel** [comment]
As far as I understand, this PR is not ready for merging yet?

**Comment by kaixih** [comment]
Certainly, kindly await our official release. After that, I will remove the draft name from the subject and notify you for review. I apologize for any confusion caused.

**Comment by gbaned** [comment]
Hi @kaixih Any update on this PR? Please. Thank you!

**Comment by kamaljeeti** [comment]
Hi @kaixih 
Any update on this PR? Please. Thank you!

**Comment by kaixih** [comment]
Removing the draft keyword, since the official release is out. PTAL. Thanks.

**Review by chsigg — APPROVED** [review]

**Comment by akuegel** [comment]
There seems to be a problem with the patch file:

Error in patch: Error applying patch /tmpfs/src/copybara/third_party/cudnn_frontend_header_fix.patch: Incorrect Chunk: the chunk content doesn't match the target
**Original Position**: 30

**Original Content**:
#include <sstream>
#include <utility>

#include <cudnn.h>
#include <cudnn_backend.h>

#include "cudnn_frontend_EngineConfig.h"
#include "cudnn_frontend_Engine.h"

**Revised Content**:
#include <sstream>
#include <utility>

#include "third_party/gpus/cudnn/cudnn.h"
#include "third_party/gpus/cudnn/cudnn_backend.h"

#include "cudnn_frontend_EngineConfig.h"
#include "cudnn_frontend_Engine.h"

**Comment by kaixih** [comment]
@akuegel Can you give more context on this? What is "Incorrect Chunk: the chunk content doesn't match the target"? I tried the patch file locally and I didn't see any issues.

**Comment by akuegel** [comment]
> @akuegel Can you give more context on this? What is "Incorrect Chunk: the chunk content doesn't match the target"? I tried the patch file locally and I didn't see any issues.

Based on the latest update for v0.9, it seems we need to pull this into our internal codebase first before we can update Tensorflow (https://github.com/tensorflow/tensorflow/pull/60379)
So please ignore this for now, we will handle it internally.

**Comment by kamaljeeti** [comment]
Hi @akuegel , any update on this PR? Please. Thank you!

**Comment by akuegel** [comment]
> Hi @akuegel , any update on this PR? Please. Thank you!

This update will need to be done internally (people started working on it). Therefore this PR can be closed.

**Comment by dimitar-asenov** [comment]
The version is now bumped to 1.0.

**Pull request closed without merging**
