### PR TITLE
Reviewed and copy edited top-level OpenXLA compiler README

### PR DESCRIPTION
**Pull request by pcoet**
I made some edits to improve readability and remove redundancy.

### CODE REVIEW

**Comment by pcoet** [comment]
@theadactyl Can you take a look at this? I did some copy editing for readability. If this looks good, I'll work through more markdown docs.

**Comment by theadactyl** [comment]
We may want to revisit the tool descriptions. If that's not a blocker to merging, happy to approve - lmk!

**Comment by pcoet** [comment]
I think it's fine to be iterative here. We can revisit the tool descriptions. I think this is an improvement over the current draft. If you agree, let's approve/merge and go from there. Thanks!

**Review by theadactyl — APPROVED** [review]

**Comment by pcoet** [comment]
Thanks, Thea! @ddunl could you merge this?

**Comment by ddunl** [comment]
Will do. Tres got the copybara magic started and it should be merged soon (pending a LGTM internally)

**Pull request closed without merging**
