### PR TITLE
[GPU][NFC] Move IsPtxRegisterAllocationError().

### PR DESCRIPTION
**Pull request by sergachev**

### CODE REVIEW

**Review by beckerhe — APPROVED** [review]
Thank you!

**Comment by derdrdirk** [comment]
`IsPtxRegisterAllocationError` is both used in `cuda_asm_compiler.cc` as well as in `ptx_compiler_impl.cc` which creates a circular build depdency:

```
.-> //third_party/tensorflow/compiler/xla/stream_executor/cuda:ptx_compiler (4f596c959f7ef923c337539a46cbb40afaddf1425e521f23a7866a7febb52cbc)
|   //third_party/tensorflow/compiler/xla/stream_executor/cuda:ptx_compiler_impl (4f596c959f7ef923c337539a46cbb40afaddf1425e521f23a7866a7febb52cbc)
|   //third_party/tensorflow/compiler/xla/stream_executor/cuda:cuda_asm_compiler (4f596c959f7ef923c337539a46cbb40afaddf1425e521f23a7866a7febb52cbc)
`-- //third_party/tensorflow/compiler/xla/stream_executor/cuda:ptx_compiler (4f596c959f7ef923c337539a46cbb40afaddf1425e521f23a7866a7febb52cbc)
```

Could you resolve the circular build dependency?

**Comment by sergachev** [comment]
I see, the circular dependency is not present in OSS because of this:
https://github.com/openxla/xla/blob/ac1ff26de37ac3ad9f1db97bf5fe4b5a5f67002c/xla/stream_executor/cuda/BUILD#L55-L68

**Review by derdrdirk — APPROVED** [review]

**Comment by derdrdirk** [comment]
Thanks for the quick fix!

**Pull request closed without merging**
