### PR TITLE
Catch exception thrown by external library.

### PR DESCRIPTION
**Pull request by nouiz**
@hawkinsp @cheshire @ezhulenev 

https://github.com/NVIDIA/TransformerEngine/ need a way to report error.

### CODE REVIEW

**Review by ezhulenev — APPROVED** [review]

**Comment by ddunl** [comment]
Our CI is very angry about exceptions being turned on. I'll leave it to @ezhulenev and @cheshire to patch or decide on the appropriate fix! (I thought `-fexceptions` would've worked well enough).

**Comment by ddunl** [comment]
@hawkinsp as he has checked in some code using `-fexceptions` prior and may know more about whether we can do this. I see that based on prior usages we probably need `-fno_strict_aliasing` and `features = ["-use_header_modules"]` but having a hard time deciding whether this usage is safe, I've seen internal discussions which seem to view checking in code with those things enabled as wildly unsafe

**Comment by cheshire** [comment]
There are many examples in TF and/or XLA using this pattern: is it possible to try to bisect how this example varies from the ones which are working?

**Comment by ddunl** [comment]
I'm speaking only from a position of caution (and likely ignorance), I don't see any difference between prior examples, but am still wary of the nastiness that can happen when we mix `-fno-exceptions` and `-fexceptions`. If it looks good to you I'll make the patch internally and see what happens

**Comment by hawkinsp** [comment]
In general this is no different to how we handle pybind11 code in, say, TF. pybind11 depends on exceptions to communicate errors.

Google's rule is that you can call third-party code that uses exceptions, but you should wrap that code to prevent exceptions escaping into code that does not expect exceptions (internal reference: go/cpp-3p-exceptions). That's what this PR does.

You do have to set some additional compiler options, as you found out.

**Pull request closed without merging**
