### PR TITLE
[xla][gpu] Adding `_xla_send_recv_validation` attribute to collective permute

### PR DESCRIPTION
**Pull request by shraiysh**
This patch computes the `_xla_send_recv_validation` attribute using the trip count and the number of devices.

### CODE REVIEW

**Comment by shraiysh** [comment]
@Tixxx @bixia1 here is the PR for the effort on adding the attribute.

**Comment by kamaljeeti** [comment]
Hi @bixia1 , can you look into this PR? Thanks.

**Comment by shraiysh** [comment]
> Hi @bixia1 , can you look into this PR? Thanks.

This is still a work in progress. There are discussions surrounding this. I converted it to a draft till the next steps are clear.

**Comment by shraiysh** [comment]
This work is now merged.

Relevant PRs (in the order they were merged):

1. https://github.com/openxla/xla/pull/12892
2. https://github.com/openxla/xla/pull/13190
3. https://github.com/openxla/xla/pull/13278
4. https://github.com/openxla/xla/pull/13555

Closing this draft PR now.

**Pull request closed without merging**
