### PR TITLE
[ROCm] Fix build issue caused by unnecessary hip_runtime.h include

### PR DESCRIPTION
**Pull request by mmakevic-amd**
Issue was introduced here: https://github.com/openxla/xla/commit/7e2ff2b1405155d7d6db6bdbca14b09165c122db

### CODE REVIEW

**Comment by beckerhe** [comment]
Hey, this seems to be fine on the CI?

Can you share the exact error that you're seeing?

I'm a bit reluctant to approve that change because I don't think the include is unecessary. The header references `hipFunction_t` therefore it should include the API header declaring that type.

**Comment by beckerhe** [comment]
Is this rocm_driver_wrapper.h related?

I've just submitted https://github.com/openxla/xla/commit/26c6f1fe46dc34a41285fe95da49093834c9d985

I'm wondering if this also fixes your issue?

**Comment by mmakevic-amd** [comment]
Yes defining `__HIP_DISABLE_CPP_FUNCTIONS__` before inclusion of `hip_runtime.h` is also alright.  I opted for using the wrapper to stay consistent with recent build fixes I found (e.g. https://github.com/openxla/xla/pull/17507)

**Comment by beckerhe** [comment]
> Yes defining `__HIP_DISABLE_CPP_FUNCTIONS__` before inclusion of `hip_runtime.h` is also alright. I opted for using the wrapper to stay consistent with recent build fixes I found (e.g. #17507)

Gotcha.

Since we try to follow the include-what-you-use scheme I would like not to remove the include in this case.

Since this is fixed due to my other change as well, can we close this or do you still see a strong reason to merge this?

**Comment by mmakevic-amd** [comment]
> Since we try to follow the include-what-you-use scheme I would like not to remove the include in this case.
> Since this is fixed due to my other change as well, can we close this or do you still see a strong reason to merge this?

Sure thing, I'll close it since it is not necessary anymore

**Pull request closed without merging**
