### PR TITLE
[XLA:CPU][oneDNN][Stale] Add post-ops for oneDNN Convolutions

### PR DESCRIPTION
**Pull request by akhilgoe**
This PR adds support for multiple post-ops for oneDNN Convolutions. New Post-ops added:

1. Relu
2. Tanh
3. Gelu (Approx.)
4. Gelu (Exact)
5. Relu6
6. Sigmoid
7. Elu
8. Elementwise scalar product

Additionally, this PR refactors the oneDNN convolution test file and adds parameterized tests for F32, BF16 and F16.

### CODE REVIEW

**Review by penpornk — CHANGES_REQUESTED** [review]
Thank you for the PR and sorry for the delay!

I think we should separate this PR into 4 PRs.
1. The refactoring in onednn_convolution_test.cc: 
    * The part where FileCheck templates are added variables $0 and $1. 
    * The update of existing test cases / make them parameterized (`TEST_P`).
 2. onednn_util changes.
     * Refactoring `PopulateOneDnnPostOps`.
     * This PR doesn't need to update a test file since it's just code refactoring.
 3. Updating HandleMaximum, etc. in onednn_contraction_rewriter.cc (that is not `HandleAdd`) to use `OneDnnFusibleInstr`.
 4. The rest of this PR. 
     * `HANDLE_OP_INTERNAL` replacement.
     * `HandleAdd` logic update. 
     * New test cases ion onednn_convolution_test.cc

**Comment by akhilgoe** [comment]
Thanks @penpornk for the review. Here is the first of the 4 PRs that you requested:

https://github.com/openxla/xla/pull/18413

I'll tag you on the other PRs when they are ready.

**Comment by akhilgoe** [comment]
Hi @penpornk, Thanks for your review! I have marked this PR as stale, and as per your suggestions split this PR into 4 PRs.

1. https://github.com/openxla/xla/pull/18413 (Merged)
2. https://github.com/openxla/xla/pull/18527 (Merged)
3. https://github.com/openxla/xla/pull/18616
4. https://github.com/openxla/xla/pull/19099

**Comment by akhilgoe** [comment]
Closing since all the split PRs are merged now.

**Pull request closed without merging**
