### PR TITLE
Changes needed for future hardware compatibility.

### PR DESCRIPTION
**Pull request by dimvar**

### CODE REVIEW

**Comment by cheshire** [comment]
Could we send/link a patch to upstream Triton?

**Comment by NaiyerRizz** [comment]
Hi @dimvar 
Can you please look into the above comment from @cheshire

**Comment by thomasjoerg** [comment]
@dimvar friendly ping!

**Comment by dimvar** [comment]
Hi, sorry for the late reply, just got back from vacation. We've modified these commits since I sent this PR. Let's close it for now, and I may open another one with the new commits later.

**Pull request closed without merging**
